### PR TITLE
azure_rm_appgateway.py: Support Version 2 SKUs

### PR DESCRIPTION
**Pull request by craigforr**
##### SUMMARY

Add support for `Standard_v2` and `WAF_v2` SKUs in azure_rm_appgateway.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure_rm_appgateway

### CODE REVIEW

**Comment by craigforr** [comment]
@haiyuazhang: It looks like you have reviewed recent pull requests.... Is there anything else I need to do here to have this reviewed?  It's a pretty simple addition of SKUs.  Looking at the history of commits for this module, @gavinfish and @Fred-sun were committers, so if I require additional reviewers, perhaps they would be good candidates.

**Comment by Fred-sun** [comment]
@craigforr Haiyuan is on vacation. When he returns, I will ping him to review. Thank you very much!

**Comment by craigforr** [comment]
@Fred-sun: Is @haiyuazhang back yet, or is there someone else who could review this PR ?

**Comment by Fred-sun** [comment]
> @Fred-sun: Is @haiyuazhang back yet, or is there someone else who could review this PR ?

He has come back and will review this PR today or tomorrow, thank you!

**Comment by Fred-sun** [comment]
@craigforr Can you add test cases for the two parameters? ---ansible_collections_azure/tests/integration/targets/azure_rm_appgateway/tasks/main.yml. I test locally and prompt Fail. Can you try with these two parameters? Thank you!
```e.g.
    "msg": "Error creating the Application Gateway instance: Azure Error: ApplicationGatewayFeatureCannotBeEnabledForSelectedSku\nMessage: Application Gateway /subscriptions/xxxxxxxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/applicationGateways/appgatewayfred02 does not support AuthenticationCertificates for the selected SKU tier WAF_v2. Supported SKU tiers are Standard,WAF."

**Comment by craigforr** [comment]
@Fred-sun: I'd be happy to add tests.  However, since the v2 SKUs do not support AuthenticationCertificates, as the error you received shows, I believe we will need to create a separate test for these SKUs.  Since I'm not familiar with your testing setup, I will need some guidance as to how you typically handle this kind of situation.  Should I create a second playbook, next to `main.yml` in `tests/integration/targets/azure_rm_appgateway/tasks/` -- for example, `skus_v2.yml` -- in order to run these tests ?

**Comment by Fred-sun** [comment]
@craigforr Yes, You can recreate an new appgateway in the current test sample ( name: "appgateway{{ rpfx }}02"  , update the SKU parameter, and delete it at the end of the test. Thank you very much!

**Comment by haiyuazhang** [comment]
I've test it, works。

**Pull request merged**
