### PR TITLE
Change network_client api_version to match latest default api_version

### LINKED ISSUE #156: azure_rm_virtualnetwork error 'APIVersion 2019-06-01 is not available'
##### SUMMARY
When using azure.azcollection.azure_rm_virtualnetwork it throws the error APIVersion 2019-06-01 is not available. Tested in published master and current dev

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_virtualnetwork

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /Users/dchaffelson/PycharmProjects/fef0/ansible.cfg
  configured module search path = ['/Users/dchaffelson/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dchaffelson/Projects/py3/fef0/lib/python3.7/site-packages/ansible
  executable location = /Users/dchaffelson/Projects/py3/fef0/bin/ansible
  python version = 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/Users/dchaffelson/PycharmProjects/fef0/ansible.cfg) = ['profile_tasks']
DEFAULT_JINJA2_NATIVE(/Users/dchaffelson/PycharmProjects/fef0/ansible.cfg) = True
```

##### OS / ENVIRONMENT

MacOX Catalina 10.15.5

##### STEPS TO REPRODUCE

```yaml
azure.azcollection.azure_rm_virtualnetwork:  # Collection version broken in 2.9.9
            resource_group: "{{ _fef0_metagroup_name }}"
            location: "{{ fef0_az_region }}"
            name: "{{ _fef0_vpcvnet_name }}"
            state: "{{ _fef0_state }}"
            address_prefixes_cidr: "{{ [fef0_vpc_cidr] }}"
            purge_address_prefixes: yes
            purge_dns_servers: yes
            tags: "{{ _fef0_default_tags }}"
```

##### EXPECTED RESULTS

In this case, the vnet should be created, which works fine with the module version i.e. using 
`azure_rm_virtualnetwork` instead of `azure.azcollection.azure_rm_virtualnetwork`

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotImplementedError: APIVersion 2019-06-01 is not available
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/dchaffelson/.ansible/tmp/ansible-tmp-1591905822.6336188-53169-51762604834540/AnsiballZ_azure_rm_virtualnetwork.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/dchaffelson/.ansible/tmp/ansible-tmp-1591905822.6336188-53169-51762604834540/AnsiballZ_azure_rm_virtualnetwork.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/dchaffelson/.ansible/tmp/ansible-tmp-1591905822.6336188-53169-51762604834540/AnsiballZ_azure_rm_virtualnetwork.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_virtualnetwork', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/4d/rv2dcypn6v3cnlh8vg2prz2m0000gp/T/ansible_azure.azcollection.azure_rm_virtualnetwork_payload_3wdxo2vy/ansible_azure.azcollection.azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 394, in <module>\n  File \"/var/folders/4d/rv2dcypn6v3cnlh8vg2prz2m0000gp/T/ansible_azure.azcollection.azure_rm_virtualnetwork_payload_3wdxo2vy/ansible_azure.azcollection.azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 390, in main\n  File \"/var/folders/4d/rv2dcypn6v3cnlh8vg2prz2m0000gp/T/ansible_azure.azcollection.azure_rm_virtualnetwork_payload_3wdxo2vy/ansible_azure.azcollection.azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 245, in __init__\n  File \"/var/folders/4d/rv2dcypn6v3cnlh8vg2prz2m0000gp/T/ansible_azure.azcollection.azure_rm_virtualnetwork_payload_3wdxo2vy/ansible_azure.azcollection.azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 418, in __init__\n  File \"/var/folders/4d/rv2dcypn6v3cnlh8vg2prz2m0000gp/T/ansible_azure.azcollection.azure_rm_virtualnetwork_payload_3wdxo2vy/ansible_azure.azcollection.azure_rm_virtualnetwork_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_virtualnetwork.py\", line 272, in exec_module\n  File \"/Users/dchaffelson/Projects/py3/fef0/lib/python3.7/site-packages/azure/mgmt/network/network_management_client.py\", line 2449, in virtual_networks\n    raise NotImplementedError(\"APIVersion {} is not available\".format(api_version))\nNotImplementedError: APIVersion 2019-06-01 is not available\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```

### PR DESCRIPTION
**Pull request by Chaffelson**
##### SUMMARY

Fixes #156 
Change network_client api_version to match latest default api_version

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_common
##### ADDITIONAL INFORMATION

```paste below
azure_rm_common uses an incorrect api_version for the network client, which in turn causes all dependent calls such as azure_rm_securitygroup to fail.
```

### CODE REVIEW

**Comment by UnwashedMeme** [comment]
works for me

**Review by UnwashedMeme — DISMISSED** [review]
This fixes the problem in my environment.

**Comment by Fred-sun** [comment]
@Chaffelson Thank you for your contribution, lowering the API version is not the best option, we should upgrade the API version, so that we can fix the problems encountered. Will you give try! Thank you! 

Modify requirements-azure.txt#L18  to azure-mgmt-network==10.2.0 


```e.g.
sudo pip3 install azure-mgmt-network==10.2.0 -I

**Comment by Fred-sun** [comment]
> This fixes the problem in my environment.

**Comment by Chaffelson** [comment]
@Fred-sun thanks for your review.
I have tried updating the network client manually and it does resolve the issue and works for my usecase, though the install produces a version conflict

`
ERROR: azure-storage-file 2.1.0 has requirement azure-storage-common~=2.1, but you'll have azure-storage-common 1.4.2 which is incompatible.
`

Admittedly I am not yet very familiar with this codebase, but If we are to update the version of the network client in the requirements file, should we not also update the 'latest' versions set in [rm_common](https://github.com/ansible-collections/azure/blob/8aad2a0c43d16cf0f5619164751e1e7049316f69/plugins/module_utils/azure_rm_common.py#L75)?

**Comment by Fred-sun** [comment]
@Chaffelson It is of course best to update to the latest version. The azure_rm_common version is only the latest version when it was added at that time, because of the API version has been updated and maintained, We will update the API version based on current needs. Thank you!

**Comment by Chaffelson** [comment]
@Fred-sun and @UnwashedMeme I have updated the commit in the PR to update the requirements and the versions in rm_common for the new version advised by @Fred-sun 
If you can review and test again that would be great.

**Comment by Fred-sun** [comment]
> @Fred-sun and @UnwashedMeme I have updated the commit in the PR to update the requirements and the versions in rm_common for the new version advised by @Fred-sun
> If you can review and test again that would be great.

@Chaffelson Thanks for your contribution. I will push for review and merge!

**Comment by Fred-sun** [comment]
@haiyuazhang Please help review and push for merge! Thank you very much!

**Pull request merged**
