### PR TITLE
Added Metadata support to azure_rm_dnsrecordset.py

### LINKED ISSUE #470: azure_rm_dnsrecordset doesn't apply metadata tags for records
##### SUMMARY
azure_rm_dnsrecordset doesn't apply metadata tags for records even with set with append_tags: yes or absent. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_dnsrecordset

##### ANSIBLE VERSION

```paste below
 [azureuser@quickstartansible-vm ~]$ ansible --version
ansible 2.10.7
  config file = /home/azureuser/.ansible.cfg
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
[azureuser@quickstartansible-vm ~]$
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

CentOS Linux release 7.9.2009 (Core)

##### STEPS TO REPRODUCE

Run below play

```yaml
  - name: Set "A" record with Public IP address
    azure_rm_dnsrecordset: # used because azure_rm_dnsrecordset doesn't allow setting DNS Alias
      resource_group: "{{ dns_resource_group }}"
      relative_name: "{{ dnshostname }}"
      zone_name: "{{ dnszone }}"
      record_type: A
      records:
        - entry: "{{ output_ip_address.state.ip_address }}"
      append_tags: yes
      tags:
        tagname: value
```

##### EXPECTED RESULTS

Metadata key of tagname and value of value should exist on dns record created

##### ACTUAL RESULTS

Metadata does not exist

```paste below
TASK [Set "A" record with Public IP address] *************************************************************************************************************************************************************************[WARNING]: Azure API profile latest does not define an entry for DnsManagementClient
ok: [localhost]
```

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Added support for attaching metadata to dnsrecordsets.

Fixes #470 

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_dnsrecordset.py
azure_rm_dnsrecordset_info.py

##### ADDITIONAL INFORMATION
DNS recordset APIs does not support tags attribute, instead it has '**metadata**' argument that needs to be used for attaching metadata information to record set.
https://docs.microsoft.com/en-us/rest/api/dns/record-sets/create-or-update

### CODE REVIEW

**Comment by Fred-sun** [comment]
@techcon65 Thank you for contributing this feature. Can you add a use case for it? Thank you very much!

**Comment by Fred-sun** [comment]
@techcon65 Please delete the statement in ignore （ignore-2.9.txt，ignore-2.10.txt，ignore-2.11.txt，ignore-2.12.txt）. Thank you very much!

```e.g.
ERROR: 
tests/sanity/ignore-2.10.txt:55:1: A100: Ignoring 'doc-missing-type' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
ERROR: tests/sanity/ignore-2.10.txt:56:1: A100: Ignoring 'parameter-type-not-in-doc' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
ERROR: tests/sanity/ignore-2.10.txt:57:1: A100: Ignoring 'doc-elements-mismatch' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
ERROR: tests/sanity/ignore-2.10.txt:59:1: A100: Ignoring 'return-syntax-error' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
ERROR: tests/sanity/ignore-2.10.txt:60:1: A100: Ignoring 'parameter-type-not-in-doc' on 'plugins/modules/azure_rm_dnsrecordset_info.py' is unnecessary
ERROR: tests/sanity/ignore-2.10.txt:61:1: A100: Ignoring 'return-syntax-error' on 'plugins/modules/azure_rm_dnsrecordset_info.py' is unnecessary

**Comment by ghost** [comment]
> @techcon65 Please delete the statement in ignore （ignore-2.9.txt，ignore-2.10.txt，ignore-2.11.txt，ignore-2.12.txt）. Thank you very much!
> 
> ```
> ERROR: 
> tests/sanity/ignore-2.10.txt:55:1: A100: Ignoring 'doc-missing-type' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
> ERROR: tests/sanity/ignore-2.10.txt:56:1: A100: Ignoring 'parameter-type-not-in-doc' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
> ERROR: tests/sanity/ignore-2.10.txt:57:1: A100: Ignoring 'doc-elements-mismatch' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
> ERROR: tests/sanity/ignore-2.10.txt:59:1: A100: Ignoring 'return-syntax-error' on 'plugins/modules/azure_rm_dnsrecordset.py' is unnecessary
> ERROR: tests/sanity/ignore-2.10.txt:60:1: A100: Ignoring 'parameter-type-not-in-doc' on 'plugins/modules/azure_rm_dnsrecordset_info.py' is unnecessary
> ERROR: tests/sanity/ignore-2.10.txt:61:1: A100: Ignoring 'return-syntax-error' on 'plugins/modules/azure_rm_dnsrecordset_info.py' is unnecessary
> ```

@Fred-sun updated the files. Thank you very much!

**Comment by ghost** [comment]
> @techcon65 Thank you for contributing this feature. Can you add a use case for it? Thank you very much!

Added the example, Thank you!

**Comment by Fred-sun** [comment]
@ghost It would be great if “tests/sanity/ignore-2.13.txt” could be updated as well! Thank you very much!

**Pull request merged**
