### PR TITLE
Remove references to Redis 4 and support upgrading to Redis 6

### PR DESCRIPTION
**Pull request by l3ender**
##### SUMMARY

Redis 4 is no longer being supported and existing instances need to be updated: https://azure.microsoft.com/en-us/updates/upgrade-your-azure-cache-for-redis-instances-to-use-redis-version-6-by-30-june-2023/

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_rediscache

##### ADDITIONAL INFORMATION

See announcement here: https://azure.microsoft.com/en-us/updates/upgrade-your-azure-cache-for-redis-instances-to-use-redis-version-6-by-30-june-2023/

Upgrading an existing instance (from 4->6) is supported (I have tested) so the module is being updated appropriately.

### CODE REVIEW

**Comment by l3ender** [comment]
@Fred-sun Hello--can you please review and advise? Thank you!

**Comment by Fred-sun** [comment]
@l3ender Great. Now I(redis_verison=4) is retired.

**Comment by xuzhang3** [comment]
@l3ender  Redis v4 is in deprecating phase and currently v4 instance can still be updated but cannot create new instance. We should let users choose whether to upgrade to v6 not totally remove v4 support which is a breaking changed.

**Comment by Fred-sun** [comment]
@xuzhang3 @l3ender I think the document annotation v4 is depreted and can be upgraded to 6, default value is v6. Thank you very much!

**Comment by Fred-sun** [comment]
kindly ping!

**Comment by l3ender** [comment]
@Fred-sun - I've updated the PR and kept support for Redis4, while setting 6 as the default and allowing upgrades from 4->6. Please review; thanks!

**Review by xuzhang3 — APPROVED** [review]

**Pull request merged**
