### PR TITLE
Fixed issue #331 removed static commercial cloud references

### PR DESCRIPTION
**Pull request by opfpqgoon**
##### SUMMARY

Fixed references to azure cloud environment statically assigned to Azure Commercial

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_keyvaultkey
azure_rm_keyvaultkeyinfo
azure_rm_keyvaultsecret
azure_rm_keyvaultsecret_info

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@opfpqgoon Thank you for your contribution, please help to fix these files conflict! Thank you very much!

**Comment by Ompragash** [comment]
@opfpqgoon Could you kindly check the file conflicts?

**Comment by Fred-sun** [comment]
kinldy ping!

**Comment by Fred-sun** [comment]
@opfpqgoon Can you help resolve conflicts in PR? We are reviewing these PR recently and pushing forward the merger. Thank you!

**Comment by Fred-sun** [comment]
duplicate with https://github.com/ansible-collections/azure/pull/356( has merged)

**Pull request closed without merging**
