### PR TITLE
 Format the md5 value returned by azure_rm_storageblob.py

### LINKED ISSUE #1015: azure_rm_storageblob returns error when trying to download a blob
##### SUMMARY
Using azure_rm_storageblob to download a blob exits in error with version 1.14 of azure collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_storageblob

##### ANSIBLE VERSION
```
ansible [core 2.13.5]
  config file = /home/ubuntu/ansible/test/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.pyenv/versions/3.8.10/envs/ansible-test2/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.pyenv/versions/ansible-test2/bin/ansible
  python version = 3.8.10 (default, Jun 27 2022, 11:26:32) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection         Version
------------------ -------
azure.azcollection 1.14.0
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/home/ubuntu/ansible/test/ansible.cfg) = ['/home/ubuntu/ansible/test/roles']
DEFAULT_STDOUT_CALLBACK(/home/ubuntu/ansible/test/ansible.cfg) = debug
HOST_KEY_CHECKING(/home/ubuntu/ansible/test/ansible.cfg) = False
INVENTORY_ENABLED(/home/ubuntu/ansible/test/ansible.cfg) = ['ini']
```

##### OS / ENVIRONMENT
Ubuntu 20.04

##### STEPS TO REPRODUCE

Create a storage account, a test container and upload a test.zip file then run the following play
```
---
- hosts: localhost
  name: Test
  tasks:
    - name: Download from Azure Blob
      azure.azcollection.azure_rm_storageblob:
        resource_group: rgname
        storage_account_name: storagename
        container: test
        blob: test.zip
        dest: ./test.zip
      delegate_to: localhost
      become: False
```

##### EXPECTED RESULTS
File is downloaded and ansible run exits in success.

##### ACTUAL RESULTS
File is downloaded but the ansible run exceptions with the following stack trace
```
TASK [Download from Azure Blob] ************************************************************************************************************************************************************************************************************
task path: /home/ubuntu/ansible/test/main.yml:5
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp `"&& mkdir "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708 `" && echo ansible-tmp-1667554951.9511242-29403-119073228271708="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708 `" ) && sleep 0'
Using module file /home/ubuntu/.ansible/collections/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py
<localhost> PUT /home/ubuntu/.ansible/tmp/ansible-local-29271qtoc_eh4/tmp9oxq68bd TO /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/ /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python3 /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 273, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
TypeError: __init__() got an unexpected keyword argument 'encoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', _modlib_path=modlib_path),
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 644, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 640, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 253, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 473, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1513, in exit_json
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1507, in _return_formatted
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1456, in jsonify
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 280, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 267, in _json_encode_fallback
TypeError: Cannot json serialize bytearray(b'\xc4n\x17\x03N\xf3\xf9&\xd6~\x01S\x17\xbd\xd8\xb1')
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1
}

MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 273, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
TypeError: __init__() got an unexpected keyword argument 'encoding'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 107, in <module>
    _ansiballz_main()
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ubuntu/.ansible/tmp/ansible-tmp-1667554951.9511242-29403-119073228271708/AnsiballZ_azure_rm_storageblob.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_storageblob', _modlib_path=modlib_path),
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 644, in <module>
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 640, in main
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_storageblob.py", line 253, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 473, in __init__
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1513, in exit_json
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1507, in _return_formatted
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/basic.py", line 1456, in jsonify
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 280, in jsonify
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/.pyenv/versions/3.8.10/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/tmp/ansible_azure.azcollection.azure_rm_storageblob_payload_dfu_vrua/ansible_azure.azcollection.azure_rm_storageblob_payload.zip/ansible/module_utils/common/text/converters.py", line 267, in _json_encode_fallback
TypeError: Cannot json serialize bytearray(b'\xc4n\x17\x03N\xf3\xf9&\xd6~\x01S\x17\xbd\xd8\xb1')
```

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

 Format the md5 value returned by azure_rm_storageblob.py, try to fixes #1015, #1032

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_storageblob.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by xuzhang3 — APPROVED** [review]

**Comment by iTiamo** [comment]
This issue is plaguing me in v1.14.0, seemingly making it impossible to upload or download any blob. When can we expect a new release of the azcollection that introduces this fix?

**Comment by Fred-sun** [comment]
@iTiamo Yes, it will be released in v1.15.0. Thanks!

**Comment by iTiamo** [comment]
@Fred-sun Thx for confirming this, but I'm mostly wondering about the schedule for azcollection releases. Considering the latest release was 4 months ago, how often can we expect releases?

**Comment by Fred-sun** [comment]
@iTiamo The exact time hasn't been set yet, but it should be soon. Thanks!

**Pull request merged**
