### PR TITLE
`azure_rm_sqlmanagedinstance` - Add support for Managed User Identities to sqlManagedInstance

### PR DESCRIPTION
**Pull request by p3ck**
##### SUMMARY
Adds support for managing User Assigned identities in sqlmanaged instances

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/module_utils/azure_rm_common_ext.py
plugins/modules/azure_rm_sqlmanagedinstance.py
tests/integration/targets/azure_rm_sqlmanagedinstance/tasks/main.yml

##### ADDITIONAL INFORMATION

I''m having difficulty testing this.  I also tried to pass in user_assigned_identities before I made this patch and it only failed for me.  So I don't believe this ever worked.

Testing is very painful because it seems to stay in a provisioning state for days.

### CODE REVIEW

**Comment by p3ck** [comment]
Ping - Can you look at this?  I am not able to run the pipelines at dev.azure.com anymore. Every time I go to the web page it signs me out of my account.

**Review by Fred-sun — APPROVED** [review]

**Comment by xuzhang3** [comment]
> Ping - Can you look at this? I am not able to run the pipelines at dev.azure.com anymore. Every time I go to the web page it signs me out of my account.

Clear the  browser cache and login in again?  Due to recent security enhancements, your login session may expire soon.

**Comment by p3ck** [comment]
> > Ping - Can you look at this? I am not able to run the pipelines at dev.azure.com anymore. Every time I go to the web page it signs me out of my account.
> 
> Clear the browser cache and login in again? Due to recent security enhancements, your login session may expire soon.

I just had to reload the page after logging in.  

https://dev.azure.com/azclitools/public/_build/results?buildId=184753&view=results

**Comment by p3ck** [comment]
ok - it took a while to understand why my test cases were failing.  But once I added a task to wait for the sqlmanaged instance to be ready everything works as expected.

https://dev.azure.com/azclitools/public/_build/results?buildId=185079&view=results

Please review now.

Thanks

**Review by Fred-sun — APPROVED** [review]

**Comment by Fred-sun** [comment]
@p3ck Yes, some resources created need to wait for the status to change back to 'succesed'. Thanks!

**Comment by Fred-sun** [comment]
@p3ck Recently, we will release a new version. But this is a minor version change that will not include this PR. In the near future we will have a breaking change, we will merge this PR. Thank you!

**Comment by p3ck** [comment]
rebased on latest dev - please review.

**Review by xuzhang3 — APPROVED** [review]

**Pull request merged**
