### PR TITLE
Add python formatting detail to contributing guide

### PR DESCRIPTION
**Pull request by l3ender**
##### SUMMARY
This PR adds documentation to the contributing guide on Python formatting rules.

##### ISSUE TYPE
- Docs Pull Request

##### ADDITIONAL INFORMATION
Derived from discussion on https://github.com/ansible-collections/azure/pull/458#issuecomment-808491136.

@paultaiton FYI.

### CODE REVIEW

**Comment by l3ender** [comment]
@Fred-sun @xuzhang3 Can you please review? I think this will be helpful for newcomers. Thank you!

**Comment by paultaiton** [comment]
Good call adding to docs

**Comment by Fred-sun** [comment]
@l3ender This addition is not recommended; ansible module development has its own code specification. In addition, Ansible has been released for a long time, and previous modules and developers have contributed to maintenance along this logic. The module is to install PEP 8 code design. Thank you very much!

**Comment by paultaiton** [comment]
@Fred-sun 
can you comment more on what coding style is in use for this project? I have in the past had blocking suggestions added to my PRs because they did not pass linting. It was only through correcting the issues identified by pycodestyle with the overrides documented here by @l3ender that I was able to avoid any more of those suggestions, which speeds up the review process and time to approval / merging.

**Comment by l3ender** [comment]
@Fred-sun Can you please advise on what the contributing document should contain? I strongly believe it should have something to assist people for this repo's guidelines.

From personal experience, when I first contributed to this repo, the pull request review came back with numerous lint findings. If the contributing doc had detail on what the maintainers of this repo expected, it would have saved time both for maintainers and for me.

**Comment by Fred-sun** [comment]
To contribute new Modules, you can refer to the link: https://staticsint.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

Please refer to the link for the document format: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html

You can test it locally before creating it, see the link: https://docs.ansible.com/ansible/latest/dev_guide/testing_documentation.html#testing-module-documentation

**Comment by l3ender** [comment]
While I think it'd be helpful to add more detail in the contributing guidelines (e.g. example config for common editors), `ansible-test sanity` covers validation for pylint. Closing the PR as it doesn't seem there is a desire to move forward with additional doc.

**Pull request closed without merging**
