### PR TITLE
Adding an all group for module_defaults

### LINKED ISSUE #569: Azure colletion is missing _action_groups_ metadata property
##### SUMMARY
Azure colletion is missing _action_groups_ metadata property which is causing some ansible functionalities to not work properly (for example module_defaults). I compared it with AWS collection (for which it is defined and it works properly): [runtime.yml](https://github.com/ansible-collections/community.aws/blob/main/meta/runtime.yml )

When I created a simple runtime file _ansible_collections/azure/azcollection/meta/runtime.yml_ 
```yaml
---
action_groups:
  azure:
  - azure_rm_resourcegroup_info
```
module_defaults worked for azure_rm_resourcegroup_info (but still didn't for other modules). 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Missing information in module metadata

##### ANSIBLE VERSION
Not relevant.

##### COLLECTION VERSION
Not relevant - checked in repo on latest version.

##### CONFIGURATION
Not relevant.

##### OS / ENVIRONMENT
Not relevant.

##### STEPS TO REPRODUCE
Run any module from connection and provide required parameters using _module_defaults_
```yaml
- block:
  - name: Check Azure Resource Group
    azure_rm_resourcegroup_info:
      name: "{{ _az_rg }}"
      list_resources: no
    register: _rg_result
  module_defaults:
    group\azure:
      client_id: "{{ _az_client_id }}"
      secret: "{{ _az_secret }}"
      subscription_id: "{{ _az_subscription_id }}"
      tenant: "{{ _az_tenant }}"
```

##### EXPECTED RESULTS
Module azure_rm_resourcegroup_info should work with parameters provided in module_defaults

##### ACTUAL RESULTS
Module fails because of missing parameters.

### PR DESCRIPTION
**Pull request by jmighion**
##### SUMMARY

This PR adds an `all` group that can target all of the provided modules from this collection when using `module_defaults`.
https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html#module-defaults-groups
Fixes #569

Future groups could be added for more separation or fine grain targeting of params, like one for `webbapp` or `virtualmachine`.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

module_defaults

##### ADDITIONAL INFORMATION

This used to work pre-collections via the Ansible upstream [module defaults](https://github.com/ansible/ansible/blob/80d8058f5c49c5d10eb3e527bd9d72052143a629/lib/ansible/config/module_defaults.yml).
People used to be able to use: 
```yaml
# example_play.yml
- hosts: localhost
  module_defaults:
    group/azure:
      subscription_id: <subscription_id>
```

That no longer works when using this collection. This PR will allow folks to something similar:
```yaml
# example_play.yml
- hosts: localhost
  module_defaults:
    group/azure.azcollection.all:
      subscription_id: <subscription_id>
```

### CODE REVIEW

**Comment by jmighion** [comment]
@Fred-sun Not sure if there's a process to get a PR triaged or marked ready for review. Let me know if I'm missing anything.

**Comment by Fred-sun** [comment]
@jmighion We are still reviewing, and the corresponding label will be labeled after the review. Thank you!

**Comment by jmighion** [comment]
Anything I can do to help the review?

**Comment by Fred-sun** [comment]
Is doing!

**Comment by Fred-sun** [comment]
@jmighion Tests have been completed and the merger will proceed as soon as possible. Thank you very much!

**Comment by xuzhang3** [comment]
@jmighion LGTM

**Comment by felixfontein** [comment]
Please note that ansible-core has a redirect from the short module dfeaults group name `azure` to `azure.azcollection.azure`. If you also add a group named `azure` and not just `all`, then users can use `group/azure` instead of `group/azure.azcollection.all` as well as described in the ansible-core documentation.

**Comment by jmighion** [comment]
I can't find it at the moment, but I'm pretty sure that the `azure` group didn't work anymore. Might need a doc update, if that assumption is right.

**Comment by felixfontein** [comment]
The `azure` group doesn't work anymore because the corresponding piece in this collection is missing / has never been added. Other groups such as `aws` and `k8s` continued to work with Ansible 2.10+ since the corresponding collections had the correct metadata matching the redirect in ansible-base/ansible-core.

**Comment by Fred-sun** [comment]
This is temporarily incorporated into the development release and will be released in the next release（v1.14.0), which we will release as soon as possible. Thank you very much!

**Comment by akira6592** [comment]
According to discussion at #977, it is better fixing [`extend_group`](https://github.com/ansible/ansible/blob/v2.13.4/lib/ansible/config/ansible_builtin_runtime.yml#L9708) from `azure.azcollection.azure` to `azure.azcollection.all` in ansible-core. Without changing the group name `all` in this collection.

I will try to fix.

**Comment by s-hertel** [comment]
This should probably be fixed in the collection. The legacy group should work regardless of the ansible-core version. If it's fixed via https://github.com/ansible/ansible/pull/78812 instead of in the collection, the collection will still be broken with with older versions of ansible-core.

Just wanted to amend my comment after looking into fixing this. At this point, there is no need to recreate an `azure` group. This was a breaking change made when the azure plugins were split into community.azure, but at this point the collection has been deprecated and all the plugins tombstoned, so there is nothing to fix anymore.

Playbooks using the legacy plugin names and legacy module_default `group/azure` will need to be rewritten at this point to use the new fully qualified collection names.

**Pull request merged**
