### PR TITLE
added computer_name parameter to available variables.

### LINKED ISSUE #279: Add computer_name to the list of host variables for azure_rm plugin
##### SUMMARY
Make Windows computer name available as host variable for azure_rm plugin, so it can be used to override `ansible_host`

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm inventory plugin

##### ADDITIONAL INFORMATION

My use cases revolves around Domain joined Azure Windows VMs without public IPs. I have Ansible controller within my domain and I use Kerberos authentication. My VM name and computer name are different, so I can't use built-in `name` host variable offered by azure_rm plugin. It works by hard-coding computer name, but ideally I would like to have `computer_name` provided by the inventory plugin similar to `name` and other host variables.

```yaml
plugin: azure_rm
auth_source: credential_file
profile: development
plain_host_names: false
include_vm_resource_groups:
  - <my-rg>
keyed_groups:
  - prefix: tag
    key: tags
hostvar_expressions:
  ansible_user: "'user@DOMAIN.LOCAL'"
  ansible_password: "'pw'"
  ansible_connection: "'winrm'"
  ansible_winrm_transport: "'kerberos'"
  ansible_winrm_server_cert_validation: "'ignore'"
  ansible_host: "computer_name + '.DOMAIN.LOCAL'"
```

### PR DESCRIPTION
**Pull request by paultaiton**
##### SUMMARY

Fixes #279 

Adds the "computer_name" property to available host variables.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure_rm.py  inventory plugin.

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@paultaiton Thank you for submitting PR, we will complete the test as soon as possible and recommend PR merger!　Thank you!

**Comment by paultaiton** [comment]
Thank you @Fred-sun

**Comment by paultaiton** [comment]
Thank you @haiyuazhang

**Comment by TiTi** [comment]
See #367

**Pull request merged**
