### PR TITLE
Add support for application gateway path-based routing

### LINKED ISSUE #448: Unable to create application gateway with path based routing
##### SUMMARY
It is not possible to use `azure_rm_appgateway` with `request_routing_rules -> rule_type = path_based_routing`. When trying to do so, an error is reported that "Request Routing Rule routing must reference a UrlPathMap". However, there is no way to configure a UrlPathMap on `azure_rm_appgateway`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_appgateway

##### ANSIBLE VERSION
```paste below
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/ross/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Dec 10 2020, 10:36:35) [Clang 12.0.0 (clang-1200.0.32.27)]
```

##### CONFIGURATION
```paste below
(no output from ansible-config dump --only-changed)
```

##### OS / ENVIRONMENT
Mac OS Big Sur 11.2.2.

##### STEPS TO REPRODUCE
```yaml
---
- name: "Playbook to create necessary application gateway."
  hosts: localhost
  connection: local

  tasks:
  - name: "Create application gateway."
    azure.azcollection.azure_rm_appgateway:
      name: "myapp-gw"
      resource_group: "myapp"
      sku:
        capacity: 1
        name: "standard_v2"
        tier: "standard_v2"
      gateway_ip_configurations:
        - name: "appGatewayIpConfig"
          subnet:
            id: /subscriptions/mysubscription/resourceGroups/myapp/providers/Microsoft.Network/virtualNetworks/myapp-vnet/subnets/default
      frontend_ip_configurations:
        - name: "public-inbound-ip"
          public_ip_address: "myapp-ip"
      frontend_ports:
        - name: "public-bound-http"
          port: 80
      backend_address_pools:
        - name: "webapp"
          backend_addresses:
            - fqdn: "myapp-webapp.azurewebsites.net"
      backend_http_settings_collection:
        - name: "webapp-profile"
          port: 443
          protocol: https
          pick_host_name_from_backend_address: true
      http_listeners:
        - name: "inbound-http"
          frontend_ip_configuration: "public-inbound-ip"
          frontend_port: "public-bound-http"
      request_routing_rules:
        - name: "http-routing"
          rule_type: "path_based_routing"
          http_listener: "inbound-http"
          backend_address_pool: "webapp"
      location: "southcentralus"
```

##### EXPECTED RESULTS
It should be possible to use `azure_rm_appgateway` with `rule_type: "path_based_routing"` and provide URL paths for routing.

##### ACTUAL RESULTS
An error is returned that URL path map is not provided.

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the Application Gateway instance: Azure Error: ApplicationGatewayRequestRoutingRuleMustReference\nMessage: Request Routing Rule /subscriptions/mysubscription/resourceGroups/myapp/providers/Microsoft.Network/applicationGateways/myapp-gw/requestRoutingRules/http-routing must reference a UrlPathMap."}
```

However, there is no property on the module to be able to configure URL path map.

### PR DESCRIPTION
**Pull request by l3ender**
##### SUMMARY
This PR adds support for using path-based routing rules in an application gateway. This allows the request to be routed to different backend pools based on the URL path.

Fixes https://github.com/ansible-collections/azure/issues/448.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/modules/azure_rm_appgateway.py

##### ADDITIONAL INFORMATION
This adds support for using `rule_type: path_based_routing` in a request routing rule. The routing rule references the URL path map resource for the gateway.

```yaml
- name: Create instance of Application Gateway with path based rules
  azure_rm_appgateway:
    ...
    request_routing_rules:
      - rule_type: path_based_routing
        http_listener: sample_http_listener
        name: rule1
        url_path_map: path_mappings
    url_path_maps:
      - name: path_mappings
        default_backend_address_pool: test_backend_address_pool
        default_backend_http_settings: sample_appgateway_http_settings
        path_rules:
          - name: path_rules
            backend_address_pool: test_backend_address_pool
            backend_http_settings: sample_appgateway_http_settings
            paths:
              - "/abc"
              - "/123/*"
```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@l3ender Thank you for your contribution. We will complete the review and push forward the merger as soon as possible! Thank you very much!

**Comment by Fred-sun** [comment]
@l3ender Lines 820,821,830,831,936,837,877, 878 and 879 continuation line over indented for visual indent! Thank you very much!

**Comment by Fred-sun** [comment]
@l3ender There is something wrong with the newly added parameter in idempotency, could you please help to check it again? Thank you very much!

**Comment by l3ender** [comment]
@Fred-sun I've corrected indentation and added a test case for idempotency. Can you please review? If you're seeing other issues with idempotency please share detail!

Thank you!

**Comment by Fred-sun** [comment]
> @Fred-sun I've corrected indentation and added a test case for idempotency. Can you please review? If you're seeing other issues with idempotency please share detail!
> 
> Thank you!

@l3ender I have tested it and there is still something wrong with the idempotency of the parameter. Could you please try again?Also, when this parameter is added, the creation resource takes too long to use. Can you do something to optimize this? Thank you very much!

**Comment by l3ender** [comment]
@Fred-sun I have corrected the idempotency issues you identified--thank you!

Regarding the time taken to create a resource with this new feature, I am seeing _very_ similar timings comparing app gateways with routing of either type (`basic` or `path_based_routing`). I tested with SKU=standard_v2 and capacity=1, and the only difference in creation being the routing type.
```
request_routing_rules:
  - rule_type: Basic
    backend_address_pool: "webapp"
    backend_http_settings: "webapp-profile"
    http_listener: "inbound-https"
    name: rule1
```
vs
```
request_routing_rules:
  - name: "url-routing"
    rule_type: "path_based_routing"
    http_listener: "inbound-https"
    url_path_map: "url-routes"
url_path_maps:
  - name: "url-routes"
    default_backend_address_pool: "webapp"
    default_backend_http_settings: "webapp-profile"
    path_rules:
      - name: "webapp-traffic"
        backend_address_pool: "webapp"
        backend_http_settings: "webapp-profile"
        paths:
          - "/myapp/*"
```

I created 3 new resources of each type and added timing around the [module's call to azure-mgmt-network](https://github.com/ansible-collections/azure/blob/f51c4b3c189a2ca7c5de05e45f34996750329d3d/plugins/modules/azure_rm_appgateway.py#L1056-L1060). Results:
* Basic: 383 seconds
* Basic: 384 seconds
* Basic: 384 seconds
* Path-based: 383 seconds
* Path-based: 383 seconds
* Path-based: 384 seconds

Please let me know if there is anything else. Thank you for your patience with me while I complete this effort!

**Comment by Fred-sun** [comment]
@l3ender I have run the test case, but there are some problems. Can you help execute the test cases（ests/integration/targets/azure_rm_appgateway/tasks/main.yml） and provide the results? . Thank you very much!

**Comment by Fred-sun** [comment]
@l3ender Could you please help to authorize me to update this PR? Thank you very much!

**Comment by l3ender** [comment]
@Fred-sun I've sent an invite so you have access to update PR. I'm still trying to figure out how to run test cases, can you please advise?

**Comment by Fred-sun** [comment]
> @Fred-sun I've sent an invite so you have access to update PR. I'm still trying to figure out how to run test cases, can you please advise?

@l3ender You can try as following playbook ( include tests/integration/targets/azure_rm_appgateway/tasks/main.yml), Also copy the file under “tests/integration/targets/azure_rm_appgateway/files/cert*.txt” to the current path.
```e.g.
---
- name: Using Azure collection
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  vars:
    resource_group: myresourcegroup
  tasks:
    - name: create resource gorup
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: eastus
    - include: main.yml

**Comment by l3ender** [comment]
@Fred-sun I have run the test using your playbook. Here is the recap:

```bash
PLAY RECAP PLAY RECAP *******************************************************************************************************
localhost                  : ok=26   changed=10   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

And here is the full execution output log: [test-results2.txt](https://github.com/ansible-collections/azure/files/6712092/test-results2.txt).

Thanks!

**Comment by l3ender** [comment]
Hi @Fred-sun, any update on this PR?

**Comment by Fred-sun** [comment]
> Hi @Fred-sun, any update on this PR?

@l3ender I will move forward with the merger as soon as possible. Thank you very much!

**Pull request merged**
