### PR TITLE
Bump version to v3.0.0

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Bump version to v2.8.0

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by p3ck** [comment]
I thought there was breaking changes in this version which would require us to move to 3.0.0?

**Review by dswan2 — APPROVED** [review]

**Review by p3ck — DISMISSED** [review]

**Review by dswan2 — APPROVED** [review]

**Comment by akira6592** [comment]
What are the breaking changes in v3.0.0 ?

I think the BREAKING CHANGES chapter should be described in CHANGELOG like [v2.0.0](https://github.com/ansible-collections/azure/releases/tag/v2.0.0).

**Comment by Fred-sun** [comment]
> What are the breaking changes in v3.0.0 ?
> 
> I think the BREAKING CHANGES chapter should be described in CHANGELOG like [v2.0.0](https://github.com/ansible-collections/azure/releases/tag/v2.0.0).

Already added! Thanks for your feedback!

**Comment by akira6592** [comment]
@Fred-sun Thank you!

**Review by dswan2 — APPROVED** [review]

**Pull request merged**
