### PR TITLE
Add NSG ruler protocol--Icmp

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Add NSG ruler protocol--Icmp.
This PR associate with [#66028](https://github.com/ansible/ansible/pull/66028).

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_securitygroup
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Fred-sun** [comment]
@haiyuazhang ready-for_review

**Review by dmlb2000 — APPROVED** [review]
I approve this request, can this be merged soon! :)

**Comment by Fred-sun** [comment]
@haiyuazhang Please help review and merge this! Thank you very much!

**Comment by norbertdalecker** [comment]
+1 @haiyuazhang can you estimate a release date. the PR is on dev branch since april.

**Pull request merged**
