### PR TITLE
Added azure cli credential support in the azure_keyvault_secret.py plugin

### LINKED ISSUE #1088: Support cli auth for azure_keyvault_secret lookup
##### SUMMARY

Most of the task plugins are supporting azure cli as credentials source.

However, the azure_keyvault_secret lookup plugin only supports MSI and Service Principal.

##### ISSUE TYPE
- Support cli auth for azure_keyvault_secret lookup

##### COMPONENT NAME
azure_keyvault_secret

##### ADDITIONAL INFORMATION

```yaml

```

### PR DESCRIPTION
**Pull request by Fred-sun**
Added azure cli credential support in the azure_keyvault_secret.py plugin， try to fixes #1088 
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_keyvault_secret.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by jkroepke** [comment]
Hi @Fred-sun, thanks a lot for this. Is there also a room for MSI auth? the modules having all the auth methods as well and MSI auth through Azure CLI wont work.

**Comment by Fred-sun** [comment]
@jkroepke This is in order!  If the ansible host is MSI enabled Azure VM, It will use MSI auth.  Thank you very much!

**Comment by jkroepke** [comment]
I could not agree by reading the code https://github.com/ansible-collections/azure/pull/1161/files#diff-3b014a0ef829e0b9df07b0d6bc06da01e063fac5dbecf71cafa8bd02aec61380R167-R176

but I will trust you.

**Comment by Fred-sun** [comment]
@jkroepke If we want to use azure cli credential, we must obtain it through subscriptioin_id, thanks!

**Review by xuzhang3 — APPROVED** [review]

**Pull request merged**
