### PR TITLE
Correct doc for azure_rm_appgateway state

### PR DESCRIPTION
**Pull request by l3ender**
##### SUMMARY
This PR corrects the documentation for `azure_rm_appgateway`, where the `state` property incorrectly mentions "public IP".

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
azure_rm_appgateway

##### ADDITIONAL INFORMATION
See also: https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_appgateway_module.html#parameter-state.

### CODE REVIEW

**Comment by l3ender** [comment]
@Fred-sun Please review...thank you!

**Comment by Fred-sun** [comment]
@l3ender Thank you for your contribution. We will complete the review and push forward the merger as soon as possible.

**Comment by l3ender** [comment]
Hello, wondering if there is anything else I can do for this PR? It is a simple doc fix.

Thank you!

**Comment by Fred-sun** [comment]
@l3ender We are reviewing and will push forward the merger as soon as possible. Thank you very much!

**Comment by xuzhang3** [comment]
LGTM

**Pull request merged**
