### PR TITLE
`azure_rm_virtualmachineextension` - Refs #1661 enable automatic update for vm extensions

### LINKED ISSUE #1661: azure_rm_virtualmachineextension/azure_rm_virtualmachineextension_info  support auto upgrade
##### SUMMARY

Currently there is no way to enable automatic upgrades on extensions. This is supported for many via 
properties.enableAutomaticUpgrade (https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-extensions/create-or-update?view=rest-compute-2024-03-01&tabs=HTTP)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachineextension
(and return info of azure_rm_virtualmachineextension_info)

##### ADDITIONAL INFORMATION

```yaml
- name: Create VM Extension
  azure_rm_virtualmachineextension:
    name: AzureMonitorLinuxAgent
    location: eastus
    resource_group: myResourceGroup
    virtual_machine_name: myvm
    publisher: Microsoft.Azure.Monitor
    virtual_machine_extension_type: AzureMonitorLinuxAgent
    type_handler_version: 1.0
    auto_upgrade_minor_version: true
    enable_automatic_upgrade: true
```

### PR DESCRIPTION
**Pull request by Klaas-**
##### SUMMARY

This partly fixes #1661

Add enable_automatic_upgrade as parameter

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure_rm_virtualmachineextension

### CODE REVIEW

**Comment by Fred-sun** [comment]
@Klaas- No problem,  if you can add “'**

> enable_automatic_upgrade': d.get('enable_automatic_upgrade', None)

**”  to azure_rm_virtualmachineextension_info.py's format_response function. It will be better. Thank you!

**Comment by Klaas-** [comment]
> @Klaas- No problem, if you can add “'**
> 
> > enable_automatic_upgrade': d.get('enable_automatic_upgrade', None)
> 
> **” to azure_rm_virtualmachineextension_info.py's format_response function. It will be better. Thank you!

Was planning on doing a 2nd PR for that, didn't get to it yet :)

**Comment by Fred-sun** [comment]
> > @Klaas- No problem, if you can add “'**
> > > enable_automatic_upgrade': d.get('enable_automatic_upgrade', None)
> > 
> > 
> > **” to azure_rm_virtualmachineextension_info.py's format_response function. It will be better. Thank you!
> 
> Was planning on doing a 2nd PR for that, didn't get to it yet :)

Yes, because you are operating on the same property, you can put it in the same PR. Thank you!

**Comment by Klaas-** [comment]
> > > @Klaas- No problem, if you can add “'**
> > > > enable_automatic_upgrade': d.get('enable_automatic_upgrade', None)
> > > 
> > > 
> > > **” to azure_rm_virtualmachineextension_info.py's format_response function. It will be better. Thank you!
> > 
> > 
> > Was planning on doing a 2nd PR for that, didn't get to it yet :)
> 
> Yes, because you are operating on the same property, you can put it in the same PR. Thank you!

done, I am unsure however if it's handled correctly, the spec is not really clear to me

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machine-extensions/get?view=rest-compute-2024-03-02&tabs=HTTP#virtualmachineextension

it says it's a boolean and always returned, but should have three states, True, False and "Not supported" or something like that, because automated updates are not supported with every extension afaik

**Review by xuzhang3 — APPROVED** [review]

**Pull request merged**
