### PR TITLE
Application gateway start/stop ability and info module

### PR DESCRIPTION
**Pull request by l3ender**
##### SUMMARY
This PR:
* adds the ability to start and stop already-created application gateways.
* adds a few additional return values for module.
* adds an info/facts module for application gateway.

##### ISSUE TYPE
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME
azure_rm_appgateway
azure_rm_appgateway_info

### CODE REVIEW

**Comment by l3ender** [comment]
@Fred-sun Please review--thank you!

**Comment by Fred-sun** [comment]
@l3ender Thank you for your contribution. We will complete the review and push forward the merger as soon as possible.

**Comment by Fred-sun** [comment]
@l3ender To be consistent with other modules, it is recommended that you merge the azure_rm_appgateway and azure_rm_appgateway_info test cases. Thank you!

**Comment by l3ender** [comment]
@Fred-sun `azure_rm_appgateway` and `azure_rm_appgateway_info` test cases have been merged. Thank you!

**Comment by xuzhang3** [comment]
@l3ender  can you help resolve the conflict?

**Comment by l3ender** [comment]
@xuzhang3 Conflicts resolved...thank you!

**Comment by xuzhang3** [comment]
LGTM

**Pull request merged**
