### PR TITLE
Bump version to v1.19.0

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Bump version to v1.19.0

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ephracis** [comment]
Would it be possible to get the encryption/security features in for 1.19.0 as well?

**Comment by Fred-sun** [comment]
@ephracis Of course, which features do you refer to and can you link the relevant PR here? I will review and improve it as soon as possible. Thank you!

**Comment by ephracis** [comment]
@Fred-sun Much appreciated! These are the PRs:

- https://github.com/ansible-collections/azure/pull/1315
- https://github.com/ansible-collections/azure/pull/1311
- https://github.com/ansible-collections/azure/pull/1310
- https://github.com/ansible-collections/azure/pull/1309
- https://github.com/ansible-collections/azure/pull/1306

I'll get working on fixing any issues you find right away as these features are a top priority for my customer.

Thanks!

**Comment by xuzhang3** [comment]
@ephracis v1.19.0 will be released.  
PRs will be include in the next version:
- https://github.com/ansible-collections/azure/pull/1315
- https://github.com/ansible-collections/azure/pull/1311
- https://github.com/ansible-collections/azure/pull/1310
- https://github.com/ansible-collections/azure/pull/1309
- https://github.com/ansible-collections/azure/pull/1306

**Review by xuzhang3 — APPROVED** [review]

**Comment by ephracis** [comment]
> @ephracis v1.19.0 will be released. PRs will be include in the next version:
> 
> * [Add auth_mode to azure_rm_storageblob #1315](https://github.com/ansible-collections/azure/pull/1315)
> * [Add encryption to azure_rm_galleryimageversion #1311](https://github.com/ansible-collections/azure/pull/1311)
> * [Add features to azure_rm_galleryimage #1310](https://github.com/ansible-collections/azure/pull/1310)
> * [Add disk_encryption_set for data disks in azure_rm_virtualmachine #1309](https://github.com/ansible-collections/azure/pull/1309)
> * [Add os_disk_encryption_set to azure_rm_virtualmachine #1306](https://github.com/ansible-collections/azure/pull/1306)

Oh, that's too bad. When do you expect the next version to be released?

**Comment by ephracis** [comment]
I see that you have a pretty decent release velocity so based on previous releases maybe I can be hopeful that these PRs will be available for the customer pretty soon. 🙂

**Comment by Fred-sun** [comment]
@ephracis Azure-graphrbac is about to be abandoned and will be replaced by msgraph. After we release this version, we will release the replacement msgraph version as soon as possible, and these PR will be released together with the next version. Thank you!

**Pull request merged**
