### PR TITLE
Fixed mismatch assignment error

### PR DESCRIPTION
**Pull request by Spacebjorn**
##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_roleassignment.py

##### ADDITIONAL INFORMATION

Errpr code: "msg": "State Mismatch Error: The assignment name exists, but does not match the provided role"

Changing the fatal message to print the elif comparison statement will show:
Error code: "msg": "role_assignment.get(): b7e6dc6d-f1e8-4753-8033-0f276bb0955b self.role_definition_id: b" 

After my suggested change the code will actually do a proper comparison ending up with:
"msg": "role_assignment.get(): b7e6dc6d-f1e8-4753-8033-0f276bb0955b self.role_definition_id: b7e6dc6d-f1e8-4753-8033-0f276bb0955b"

Trying to rerun the code below will result in the error saying there's a mismatch between the roles even though a  azure.azcollection.azure_rm_roleassignment_info task to the role will show they're the exact same.

```YML
    azure.azcollection.azure_rm_roleassignment:
      name: "{{ (ansible_azure_subscription_id + '/' + managed_identity_id + '/b7e6dc6d-f1e8-4753-8033-0f276bb0955b') | to_uuid }}"
      scope:
        "/subscriptions/{{ ansible_azure_subscription_id }}\
        /resourceGroups/{{ resource_group_name }}\
        /providers/Microsoft.Storage/storageAccounts/{{ storage_account_name }}"
      assignee_object_id: "{{ managed_identity_id }}"
      role_definition_id:
        "/subscriptions/{{ ansible_azure_subscription_id }}\
        /providers/Microsoft.Authorization/roleDefinitions/b7e6dc6d-f1e8-4753-8033-0f276bb0955b"
      state: present
```

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@Spacebjorn  Line306 should not be consistent with the change here! Thank you very much!
https://github.com/ansible-collections/azure/blob/d79a5f1c0aaad566fc6807187d7759b8278b0ad5/plugins/modules/azure_rm_roleassignment.py#L306

**Comment by Spacebjorn** [comment]
@Fred-sun  Should be fixed for both lines now. Good catch

**Comment by paultaiton** [comment]
@Spacebjorn 
Nice fix. I think I developed the faulty bit before I fully understood how to run the integration tests, because how they're written it should have caught this bug.

**Comment by Spacebjorn** [comment]
@paultaiton I would've thought the integration tests would run as prereq before merging as well?

**Comment by Spacebjorn** [comment]
@Fred-sun  Not to be rude, but is there any status on this PR? It doesn't change that much and the task is still broken if you rerun it

**Comment by xuzhang3** [comment]
@Spacebjorn LGTM

**Pull request merged**
