### PR TITLE
Add support 'node_taints' for azure_rm_aksagent.py

### LINKED ISSUE #1684: Agent Pool should allow setting a Taint
[ ]

##### SUMMARY

AKS node pools have the ability to test a list of taints but this parameter seems to be missing from the azure.azcollection.azure_rm_aksagentpool
##### ISSUE TYPE
- Feature Idea
support this setting with a list of string similar to TF. 
##### COMPONENT NAME

azure.azcollection.azure_rm_aksagentpool
##### ADDITIONAL INFORMATION

When creating the aks agent pool the user can specify n or n+1 taints

```yaml

taints: 
   - "nodeType=testy:NoSchedule"

```

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Add support 'node_taints' for azure_rm_aksagent.py， try to fixes #1684

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure_rm_aksagent.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by kbocock-krg** [comment]
ETA for release?

**Review by kbocock-krg — APPROVED** [review]
Looks good. Assume tested.

**Review by xuzhang3 — APPROVED** [review]

**Review by xuzhang3 — APPROVED** [review]

**Comment by xuzhang3** [comment]
> kbocock-krg

end of Aug

**Comment by xuzhang3** [comment]
@kbocock-krg [v2.7.0](https://github.com/ansible-collections/azure/releases/tag/v2.7.0) has been released.

**Pull request merged**
