### PR TITLE
Add max_message_size_in_kilobytes to azure_rm_servicebusqueue.py

### LINKED ISSUE #1003: Add support to set message size on azure_rm_servicebusqueue and azure_rm_servicebustopic
##### SUMMARY
azure_rm_servicebusqueue and azure_rm_servicebustopic doesn't allow to set message size

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
azure.azcollection.azure_rm_servicebusqueue

##### ADDITIONAL INFORMATION
Premium namespaces allow to set message sizes, but Ansible doesn't support this.

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Add max_message_size_in_kilobytes to azure_rm_servicebustopic.py and  azure_rm_servicebusqueue.py, try to fix #1003 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

azure_rm_servicebustopic.py
azure_rm_servicebusqueue.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by madmalkav** [comment]
Description on all files seems to be wrong? Browsing from my phone so not sure I’m looking at at correctly

**Comment by Fred-sun** [comment]
> Description on all files seems to be wrong? Browsing from my phone so not sure I’m looking at at correctly

@madmalkav Thanks for your check! Already update!

**Review by xuzhang3 — DISMISSED** [review]

**Review by xuzhang3 — APPROVED** [review]

**Comment by madmalkav** [comment]
This doesn't appear in the changelog of version 1.15.0 , has it been integrated on that version or is it waiting for a future date?

**Comment by xuzhang3** [comment]
@madmalkav  This feature should be available in v1.15.0

**Comment by madmalkav** [comment]
But it isn’t , look at the code, it is not there. 1.15.0 was release based in code from beginning of March

**Comment by xuzhang3** [comment]
@madmalkav  Rechecked the code and release timeline, this feature not released and will be available in v1.16.0. Sorry for the inconvenience

**Comment by madmalkav** [comment]
What sense does it make to hold code that is already implemented and make customers wait for months to add support for a single parameter in an already implemented module?

**Pull request merged**
