### PR TITLE
Update azure.mgmt.web

### PR DESCRIPTION
**Pull request by l3ender**
##### SUMMARY
This PR updates `azure.mgmt.web` to the latest version. The version was quite old, so this change will help bring the latest SDK updates into the collection and avoid conflicts with other tools like azure-cli.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
azure_rm_appserviceplan
azure_rm_appserviceplan_info
azure_rm_functionapp
azure_rm_functionapp_info
azure_rm_webapp
azure_rm_webapp_info
azure_rm_webappslot

##### ADDITIONAL INFORMATION

The following were removed from `azure_rm_webapp` input parameters as they are not used and I cannot find any reference to them in the SDK (old or new version). For backwards compatibility, I have kept them remaining as output parameters.
* dns_registration
* skip_custom_domain_verification
* ttl_in_seconds

I have run sanity and integration tests to verify functionality:
```bash
ansible-test sanity azure_rm_appserviceplan --color --junit -v
ansible-test sanity azure_rm_functionapp --color --junit -v
ansible-test sanity azure_rm_webapp --color --junit -v
ansible-test sanity azure_rm_webappslot --color --junit -v

ansible-test integration azure_rm_appserviceplan --allow-destructive -v --allow-unstable
ansible-test integration azure_rm_functionapp --allow-destructive -v
ansible-test integration azure_rm_webapp --allow-destructive -v
```

**Important!!!** The azure_rm_webapp integration tests require `RESOURCE_GROUP` and `RESOURCE_GROUP_SECONDARY` to be in the same region.

### CODE REVIEW

**Comment by l3ender** [comment]
@Fred-sun @xuzhang3 This PR is ready. Please take a look and let me know if I can enhance anything. Thank you!

**Comment by Fred-sun** [comment]
@l3ender Why delete parameters "dns_registration" and "skip_custom_domain_verification" for "azure_rm_webapp "?

**Comment by l3ender** [comment]
@Fred-sun I couldn't find any reference to the parameters in the SDK (old or new version) and they were not used anywhere, so I thought it best to just remove them. Thanks!

**Comment by Fred-sun** [comment]
> @Fred-sun I couldn't find any reference to the parameters in the SDK (old or new version) and they were not used anywhere, so I thought it best to just remove them. Thanks!

Yes, these two parameters will not be available in the version after the release of 2016-08-01. We will reply after discussion. Thank you very much!

**Comment by Fred-sun** [comment]
@l3ender delete https://github.com/ansible-collections/azure/blob/532d2fc71dab481f58e6d23d420e8a96faafa398/tests/integration/targets/azure_rm_webapp/tasks/main.yml#L61

**Comment by l3ender** [comment]
@Fred-sun updated!

**Comment by Fred-sun** [comment]
@l3ender Function name not found in module "azure_rm_webappvnetconnection.py"!

**Comment by l3ender** [comment]
> @l3ender Function name not found in module "azure_rm_webappvnetconnection.py"!

Updated in https://github.com/ansible-collections/azure/pull/849/commits/94f83e9c67e97b9bbab5bafd654addae3a390cf8. Thank you!

**Comment by Fred-sun** [comment]
@l3ender To create the "web app service" has a set of default ipSecurityRestrictions and scmIpSecurityRestrictions, So the test cases' "tests/integration/the targets/azure_rm_webappaccessrestriction/tasks/main yml" changes to do synchronization. Thank you very much!
```e.g.
The default information is：
                "ipSecurityRestrictions": [
                    {
                        "ipAddress": "Any",
                        "action": "Allow",
                        "priority": 1,
                        "name": "Allow all",
                        "description": "Allow all access"
                    }
                ],
                "scmIpSecurityRestrictions": [
                    {
                        "ipAddress": "Any",
                        "action": "Allow",
                        "priority": 1,
                        "name": "Allow all",
                        "description": "Allow all access"
                    }
                ],
                "scmIpSecurityRestrictionsUseMain": false,

**Comment by l3ender** [comment]
@Fred-sun - sorry for the delay. I have resolved in https://github.com/ansible-collections/azure/pull/849/commits/7765214d912874b9213e2813a3567e192a894b1e, which filters out the Azure default rules (which are not editable by user).

Thank you!

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by xuzhang3** [comment]
@l3ender  LGTM

**Pull request merged**
