### PR TITLE
Add new choices for azure_rm_postgresqlflexibleserver.py's version

### LINKED ISSUE #1648: azure_rm_postgresqlflexibleserver - Add Supported PostgreSQL Major Versions 14, 15 & 16
##### SUMMARY

Add  Azure Supported PostgreSQL Major Versions 14, 15 & 16

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

azure_rm_postgresqlflexibleserver
##### ADDITIONAL INFORMATION

Customers want access to newer PostgreSQL major versions.

```yaml

```

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Add new choices for azure_rm_postgresqlflexibleserver.py's version, try to fixes #1648

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

azure_rm_postgresqlflexibleserver.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by bmckerr-MSFT — APPROVED** [review]
11 thru 16 are Generally Available with Azure PostgreSQL Flexible Server https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions

**Review by bmckerr-MSFT — COMMENTED** [review]
Versions now reflect supported Azure PostgreSQL Flexible server major versions on Azure.

**Review by gbowerman — APPROVED** [review]

**Comment by gbowerman** [comment]
#sign-off

**Comment by gbowerman** [comment]
@xuzhang3 please can you review

**Review by xuzhang3 — APPROVED** [review]

**Comment by bmckerr-MSFT** [comment]
@xuzhang3 - Do you have any estimate on when the changes will be available in Ansible Galaxy ?

**Comment by xuzhang3** [comment]
@bmckerr-MSFT new version is planned to be released at the end of August

**Pull request merged**
