### PR TITLE
Fix dynamic VM fetch failure when I(batch_fetch=true)

### LINKED ISSUE #1328: azure_rm inventory batch_fetch not working in v1.19.0
##### SUMMARY

After upgrading my azure collection from 1.18.1 to 1.19.0, a dynamic inventory I've been using stopped working. The error seems to have to do with the `batch_fetch` functionality when running against an Azure subscription with many VMs. I'm seeing this behavior with a subscription that has 71 VMs, but not seeing it with one that has 8 VMs. The issue doesn't happen with v1.18.1 of the azure collection.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure.azcollection.azure_rm inventory – Azure Resource Manager inventory plugin

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.6]
  config file = /Users/Chip.Selden/Documents/_GIT/ansible-azure-test/ansible.cfg
  configured module search path = ['/Users/Chip.Selden/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/Chip.Selden/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/bin/ansible
  python version = 3.9.17 (main, Jun 20 2023, 17:20:08) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/lib/python3.9/site-packages/ansible_collections
Collection         Version
------------------ -------
azure.azcollection 1.19.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/Chip.Selden/Documents/_GIT/ansible-azure-test/ansible.cfg
INVENTORY_ANY_UNPARSED_IS_FAILED(/Users/Chip.Selden/Documents/_GIT/ansible-azure-test/ansible.cfg) = True
INVENTORY_ENABLED(/Users/Chip.Selden/Documents/_GIT/ansible-azure-test/ansible.cfg) = ['azure_rm']
```

##### OS / ENVIRONMENT

The machine I'm running ansible from is macOS Ventura. I have also seen this issue when running through AWX in a Centos Execution Environment.

##### STEPS TO REPRODUCE

1. Create and activate a python virtual environment with:
   * python 3.9+
   * ansible 8.4.0+
   * the packages from requirements-azure.txt
3. Create an empty playbook directory and move to it
4. Create the `ansible.cfg` file below
5. Create the `azure_rm.yml` inventory file below
   * This uses `batch_fetch: true` which is the default
6. Log in to azure using `az login`
   * The azure account I'm experiencing this with has 71 VMs
   * This issue does not occur with a different account which only has 8 VMs
8. Run the `generate inventory` command below --> FAILS
9. Change `batch_fetch` to `false` in `azure_rm.yml`
10. Run the `generate inventory` command below --> SUCCEEDS

```yaml
# ansible.cfg 
[inventory]
any_unparsed_is_failed = true
enable_plugins = azure_rm

# azure_rm.yml
---
plugin: azure.azcollection.azure_rm
subscription_id: "some-subscription-id"
batch_fetch: true

# generate inventory
ansible-inventory -i azure_rm.yml --list -vvvv --output inventory.log
```

##### EXPECTED RESULTS

The inventory file to parse without error.

##### ACTUAL RESULTS

The inventory file fails to parse due to a json decoding issue during the second execution of the _send_batch method from _process_queue_batch. The response body from the second call is an empty byte string.

```paste below
ansible-inventory [core 2.15.6]
  config file = /Users/Chip.Selden/Documents/_GIT/ansible-azure-test/ansible.cfg
  configured module search path = ['/Users/Chip.Selden/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/Chip.Selden/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/bin/ansible-inventory
  python version = 3.9.17 (main, Jun 20 2023, 17:20:08) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /Users/Chip.Selden/Documents/_GIT/ansible-azure-test/ansible.cfg as config file
setting up inventory plugins
Loading collection ansible.builtin from 
redirecting (type: inventory) ansible.builtin.azure_rm to azure.azcollection.azure_rm
Loading collection azure.azcollection from /Users/Chip.Selden/.ansible/collections/ansible_collections/azure/azcollection
[WARNING]:  * Failed to parse /Users/Chip.Selden/Documents/_GIT/ansible-azure-test/azure_rm.yml with
ansible_collections.azure.azcollection.plugins.inventory.azure_rm plugin: Expecting value: line 1 column 1 (char 0)
  File "/Users/Chip.Selden/.local/share/virtualenvs/ansible-azure-test-g8mmdU37/lib/python3.9/site-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/Users/Chip.Selden/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 220, in parse
    self._get_hosts()
  File "/Users/Chip.Selden/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 283, in _get_hosts
    self._process_queue_batch()
  File "/Users/Chip.Selden/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 414, in _process_queue_batch
    batch_resp = self._send_batch(batch_requests)
  File "/Users/Chip.Selden/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 445, in _send_batch
    return json.loads(response.body())
  File "/usr/local/Cellar/python@3.9/3.9.17_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.17_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.17_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
ERROR! Completely failed to parse inventory source /Users/Chip.Selden/Documents/_GIT/ansible-azure-test/azure_rm.yml
```

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Fix dynamic VM fetch failure when I(batch_fetch=true), fixes #1328 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by xuzhang3 — APPROVED** [review]

**Comment by TiTi** [comment]
Damn this is still not in https://pypi.org/project/ansible/#files (currently 9.4.0)

**Comment by Fred-sun** [comment]
@TiTi What version of aze.azcollection did you install, and the new changes are released in the version that incorporates this PR. Thank you!

**Comment by TiTi** [comment]
I had an azure inventory failure for a very specific resource group (using `include_vm_resource_groups`).
Other resource group in the same subscription was ok (loading fine), but this resource group had more resources (50+ vms) and was unable to list the vms, with a weird json error in -vvvv, which led me to this fix after troubleshooting manually with `batch_fetch` and `az rest`.

I had the azure.azcollection which is included in the "ansible" latest pip package (currently 9.4.0).
@Fred-sun Currently, the ansible 9.4.0 package includes azure.azcollection v1.19.0

Manually installing latest azure.azcollection (2.3.0) [with `ansible-galaxy collection install azure.azcollection`] + requirements ([cf docs](https://galaxy.ansible.com/ui/repo/published/azure/azcollection/docs/)) added this fix and thus resolved my issue : inventory loaded properly with default batch_fetch=true

I'm surprised this fix from end of november hasn't got to latest "ansible" pip package that's all.

**Comment by Fred-sun** [comment]
@TiTi azure.azcollection is a part of ansible collection, which is managed through ansible-galaxy. You can only install ansible with pip and then install azure.azcollection with ansible tool ansible-galaxy. Thank you!

**Comment by TiTi** [comment]
That's incorrect @Fred-sun 
Once you install ansible with pip, you get a lot of collections included.
See my link before and this capture :
image

This actually represents the biggest part of the tarball file.

One can also think those are 'compatible' collections with selected ansible version.

ansible-galaxy is certainly the way to go. But then, why (outdated) collections are pre-installed in the 'ansible' pip module?

**Pull request merged**
