### PR TITLE
Support azure cli credentials with multiple `subscription_id`s

### LINKED ISSUE #321: Modules ignore `subscription_id` when using CLI auth
A playbook, e.g.
```
- name: Create Azure VMs
  strategy: free
  hosts:
    - localhost
  gather_facts: false

  roles:
    - { role: azure.azure_preview_modules }
  tasks:
    - name: "Create Resource group"
      delegate_to: localhost
      azure_rm_resourcegroup:
        name: "foobar"
        location: "eastus2"
        auth_source: cli
        subscription_id: "ecb1bdd8-..."
```
Ignores the `subscription_id` field:

```
$ az account list --verbose --query '[*].{id:id,isDefault:isDefault,state:state}'
[
  {
    "id": "f1c043c7-...",
    "isDefault": true,
    "state": "Enabled"
  },
  {
    "id": "ecb1bdd8-...",
    "isDefault": false,
    "state": "Enabled"
  }
]

$ ansible-galaxy install --force azure.azure_preview_modules                                                                                                                                                      
- changing role azure.azure_preview_modules from 2.8.0 to unspecified                                                                                                                                             
- downloading role 'azure_preview_modules', owned by azure                                                                                                                                                        
- downloading role from https://github.com/Azure/azure_preview_modules/archive/2.9.0.tar.gz                                                                                                                       
- extracting azure.azure_preview_modules to ~/.ansible/roles/azure.azure_preview_modules                                                                                
- azure.azure_preview_modules (2.9.0) was installed successfully                                           

$ ansible-playbook -v subtest.yml
PLAY [Create Azure VMs] *******************************************************************************************************************************************************************************************

TASK [azure.azure_preview_modules : debug] ************************************************************************************************************************************************************************
skipping: [localhost] => 

TASK [Create Resource group] **************************************************************************************************************************************************************************************
ok: [localhost -> localhost] => changed=false 
  contains_resources: false
  state:
    id: /subscriptions/f1c043c7-.../resourceGroups/foobar
    location: eastus2
    name: foobar
    provisioning_state: Succeeded
    tags: {}

```

Note that even though I specifically asked for the rg to be created in "ecb1bdd8-..." it was created in "f1c043c7-...". 

This is especially frustrating when dealing with things that span multiple subscriptions. E.g. I want to look up vnet facts in one subscription to use it for a VM on the other subscription. Or I have a playbook that is creating a VM on each subscription.

My work around at the moment is: 
```
    - name: "Ensure the correct subscription"
      delegate_to: localhost
      shell: "az account set -s {{ subscription }}"
```
but this fails when trying to run for multiple inventory items simultaneously (e.g. build 1 vm on each vm).

### LINKED ISSUE #63182: [inventory/azure_rm] auth_source: cli doesn't honour subscription_id setting
##### SUMMARY
When using `auth_source: cli` it seems impossible to get information from other subscriptions than the default subscription (set using `az account set --subscription <id>`).

For example I have 3 subscriptions: aaa, bbb and ccc. aaa is my default subscription. My inventory config looks like:

```
plugin: azure_rm
subscription_id: bbb
auth_source: cli
```
This still returns the VMs for subscription aaa. I traced it to line 1220 in `azure_rm_common.py` where it overrides the set ID from the cli env. 

I need a way to preferably:
1. Scan all VMs from all my subscriptions (aaa, bbb, ccc) except the ones I could specify in a filter (I guess this is a feature request)
2. Scan VMs in a subscription that is different than my default subscription using the subscription_id setting

ATM I believe this is only possible with auth_source:credential_file and the corresponding profile setting

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure inventory plugin

##### ANSIBLE VERSION

```paste below
ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/geertn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/geertn/.virtualenvs/testansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/geertn/.virtualenvs/testansible/bin/ansible
  python version = 2.7.16 (default, Jul  9 2019, 16:43:02) [GCC 8.3.0]
```

##### CONFIGURATION

```paste below
(testansible) geertn@asdfdskj:~/work-fl/ansible$ ansible-config dump --only-changed
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INVENTORY_ENABLED(env: ANSIBLE_INVENTORY_ENABLED) = [u'ini', u'constructed', u'azure_rm']
(testansible) geertn@asdfdskj:~/work-fl/ansible$ 
```

### PR DESCRIPTION
**Pull request by internetionals**
This is the same change I have a pull request for at the Ansible main repository, but it isn't entirely clear what the correct path for new changes is for the Azure Ansible modules.

See original pull request: ansible/ansible#65331
(and also: Azure/azure_preview_modules#358)

I also couldn't find the doc_fragments part from the original change, so this change doesn't update the documentation, which the original does.

Also relates to these issues/pull requests in the main Ansible repository:

- ansible/ansible#48089
- ansible/ansible#63182

Below is the text from the pull request against the main Ansible repository:

##### SUMMARY
When using credentials obtained from the azure cli only the default subscription can be used, even though the azure cli is authenticated for multiple subscriptions.

This change passes any optionally specified `subscription_id` (similar to how it's done for `auth_source: msi`) along when requesting the azure cli credentials. If none is specified it falls back to the current behaviour of selecting the default subscription.

The only other change that had to be made was in the `auth_source: auto` case where we would always assume that all credential information is passed using arguments when `subscription_id` is set. I changed this to check the fields that actually refer to specific credentials (namely `client_id` (for service principals) and `ad_user` (for user names)). This way we still fall through to the azure cli method, eventhough only `subscription_id` is explicitly set.

Fixes ansible/ansible#63182
Fixes Azure/azure_preview_modules#321

This effectively fixes the same problem as ansible/ansible#48089 is trying to fix, only in a way that is more consistent with how credentials and subscription id's are determined for other `auth_source`s. This was one of the main criticisms that's probably holding that pull request up.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
azure_rm_common

##### ADDITIONAL INFORMATION
We have different Azure subscriptions for our prod and dev environments. By default we only work on the dev environment, but we have a number of playbooks that we want to work with all virtual machines at once.

Demonstration playbook:
```
- name: Get azure vm info from different subscriptions
  hosts: localhost
  tasks:
  - azure_rm_virtualmachine_info:
      name: prod-db
      resource_group: prod
      subscription_id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
      auth_source: cli
  - azure_rm_virtualmachine_info:
      name: dev-db
      resource_group: dev
      subscription_id: YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY
      auth_source: cli
```

Before:
```
$ ansible-playbook playbooks/az_info.yml

PLAY [Get azure vm info from different subscriptions] *********************************************************************************

TASK [azure_rm_virtualmachine_info] ***************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg: |-
    Error getting virtual machine prod-db - Azure Error: ResourceGroupNotFound
    Message: Resource group 'prod' could not be found.

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

After:
```
$ ansible-playbook playbooks/az_info.yml

PLAY [Get azure vm info from different subscriptions] *********************************************************************************

TASK [azure_rm_virtualmachine_info] ***************************************************************************************************
ok: [localhost]

TASK [azure_rm_virtualmachine_info] ***************************************************************************************************
ok: [localhost]

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### CODE REVIEW

**Comment by internetionals** [comment]
Sadly, I'm currently a bit overwhelmed by these CI failures and I don't have the time to triage them. But cursory glance suggests that they have nothing to do with the changes in this pull request.

**Comment by Fred-sun** [comment]
@internetionals Thank you for your interest in ansible-colleciton-azure. Recently, azure-cli is converting the mechanism of using credentials. For the PR you submitted, we will consider merging after the mechanism is modified.

**Comment by internetionals** [comment]
@Fred-sun Thanks for the update, keep us posted :-)

**Comment by bailsman** [comment]
Hi @Fred-sun. Is there anywhere I can follow the progress on the azure-cli mechanism change? Where's that discussion happening? I'm quite interested in this pull request.

**Comment by Fred-sun** [comment]
> Hi @Fred-sun. Is there anywhere I can follow the progress on the azure-cli mechanism change? Where's that discussion happening? I'm quite interested in this pull request.

Thank you for your pay attention on this. I'm sorry for not replying this question in time. I will ping Community developers to prioritize this PR tomorrow. Thank you very much!

**Comment by Fred-sun** [comment]
@internetionals Can you help resolve the conflicting files? Thank you very much!

**Comment by UnwashedMeme** [comment]
@Fred-sun @internetionals I rebased in #195 and added/fixed up the docs.  There are a few other small patches in there too. But I'm also happy to split those into separate PRs if you prefer.

**Comment by internetionals** [comment]
@Fred-sun @UnwashedMeme : I rebased my changes and included the doc-changes from my original pull request against the azure repository. The changes by @UnwashedMeme are a bit more extensive but also more comprehensive, those would be equally fine by me.

**Comment by Fred-sun** [comment]
> @Fred-sun @UnwashedMeme : I rebased my changes and included the doc-changes from my original pull request against the azure repository. The changes by @UnwashedMeme are a bit more extensive but also more comprehensive, those would be equally fine by me.

Thanks for your udpate! I will test it!

**Comment by Fred-sun** [comment]
It has added by #195, closed this!

**Pull request closed without merging**
