### PR TITLE
Fix doc link in README

### PR DESCRIPTION
**Pull request by akira6592**
##### SUMMARY

Fix link doc badge.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- README.md

##### ADDITIONAL INFORMATION

```paste below
N/A
```

### CODE REVIEW

**Review by xuzhang3 — APPROVED** [review]

**Comment by xuzhang3** [comment]
@akira6592 LGTM

**Comment by akira6592** [comment]
Thank you for merge!

**Comment by madmalkav** [comment]
This links to version 1.15.0 documentation, when the collection is already on version 1.16.0

**Comment by akira6592** [comment]
@madmalkav 
Now `latest` Ansible Community Package document is based on Ansible 8.0.0. It [includes azure.azcollection 1.15.0](https://github.com/ansible-community/ansible-build-data/blob/main/8/ansible-8.0.0.deps#L11).

When Ansible 8.1.0 release, maybe it will show 1.16.0.

**Pull request merged**
