### PR TITLE
Azure storage file share module

### LINKED ISSUE #502: Azure Files modules required
##### SUMMARY

Azure Storage have a capability that called [Azure Files](https://docs.microsoft.com/en-us/azure/storage/files/)
##### ISSUE TYPE
Currently there is no such implementation

##### COMPONENT NAME
azure_rm_storage_share
azure_rm_storage_share_info

##### ADDITIONAL INFORMATION

It will increase coverage of the basics azure features

### PR DESCRIPTION
**Pull request by ewsct**
##### SUMMARY

Azure Storage may contain [File share](https://docs.microsoft.com/en-us/azure/storage/files/). This module allows to manage such resource with Ansible.

Fixes #502 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME

- azure_rm_storageshare
- azure_rm_storageshare_info

##### ADDITIONAL INFORMATION

Adds a module to create/update/delete storage share in existing storage account. Another module fetches info about the storage share.

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@ewscat Please add "azure_rm_storageshare" to pr-pipeline.yml, Thank you very much!

**Comment by ewsct** [comment]
> @ewscat Please add "azure_rm_storageshare" to pr-pipeline.yml, Thank you very much!

done

**Comment by ewsct** [comment]
@Fred-sun may I kindly ask you to point reviewer's attention to this PR, if that is possible

**Comment by Fred-sun** [comment]
> @Fred-sun may I kindly ask you to point reviewer's attention to this PR, if that is possible

@ewscat Ok, because I was busy upgrading SDK recently, I didn't push it in time. I will push the merger as soon as possible. Thank you very much!

**Comment by xuzhang3** [comment]
@ewscat  LGTM

**Pull request merged**
