### PR TITLE
fix a typo error. related to #757

### LINKED ISSUE #757: Managed Identity auth_source: msi no longer works with collection 1.11, returns KeyError: 'credential'
##### SUMMARY
In azure.azcollection version 1.10 managed identity auth_source: msi on tasks worked without errors.
Starting with azure.azcollection version 1.11 we get a traceback error on the file azure_rm_common.py with KeyError: 'credential'
This error happens when calling any of the modules in the collection.
Looking at the code for azure_rm_common.py three things are apparent 
1) the credentials are good since the def _get_msi_credentials is not returning the defined error message for missing or bad credentials and 
2) something is looking for 'credential' singular and the def _get_msi_credentials only returns 'credentials' plural and 
3) a similar issue related to CLI credentials seems to have been fixed in DEV recently in the def _get_azure_cli_credentials area by adding a line 'credential': credentials to add the singular version.
When manually editing the file azure_rm_common.py we were able to fix the managed identity issues.
We found two different modifications in azure_rm_common.py that both work and don't know which one is correct:
1) In def _get_msi_credentials section on lines 1593:1608 add a new line in the return area to add 'credential': credentials
2) In this IF section on lines 1506:1509 modify the last line to change 'credential' to 'credentials'
        if self.credentials.get('credentials') is not None:
            # AzureCLI credentials
            self.azure_credentials = self.credentials['credentials']
            self.azure_credential_track2 = self.credentials['credential']
Don't know the code well enough to understand which of these two fixes would correct the root bug versus masking it.
 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
azure_rm_common.py

##### ANSIBLE VERSION
Multiple

##### COLLECTION VERSION

azure.azcollection 1.11.0

##### STEPS TO REPRODUCE

Create a managed identity in Azure with contributor role on the subscription to be tested.
Run a playbook using any module and the auth_source: msi setting

```yaml
  tasks:
    - name: "Test azure_rm_securitygroup_info"
      azure.azcollection.azure_rm_securitygroup_info:
        subscription_id: "{{ nsg_msi_test_sub }}"
        resource_group: "{{ nsg_msi_test_rg }}"
        name: "{{ nsg_msi_test_name }}"
        auth_source: msi
```

##### EXPECTED RESULTS

We expect the managed identity to work and allow the module to execute sucessfully.

##### ACTUAL RESULTS

What actually happens is a traceback error that ends in KeyError: 'credential'

```paste below
{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1644429743.4528656-96-165730162148775/AnsiballZ_azure_rm_securitygroup_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1644429743.4528656-96-165730162148775/AnsiballZ_azure_rm_securitygroup_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1644429743.4528656-96-165730162148775/AnsiballZ_azure_rm_securitygroup_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_securitygroup_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup_info.py\", line 393, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup_info.py\", line 389, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup_info.py\", line 335, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 464, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1509, in __init__\nKeyError: 'credential'\n",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1644429743.4528656-96-165730162148775/AnsiballZ_azure_rm_securitygroup_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1644429743.4528656-96-165730162148775/AnsiballZ_azure_rm_securitygroup_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1644429743.4528656-96-165730162148775/AnsiballZ_azure_rm_securitygroup_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_securitygroup_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup_info.py\", line 393, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup_info.py\", line 389, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_securitygroup_info.py\", line 335, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 464, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_securitygroup_info_payload_ux3w469s/ansible_azure.azcollection.azure_rm_securitygroup_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 1509, in __init__\nKeyError: 'credential'\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}
```

### PR DESCRIPTION
**Pull request by danielino**
##### SUMMARY
there is an issue with MSI Authentication.

Fixes #757 

```
Loading collection azure.azcollection from /home/jenkins/.ansible/collections/ansible_collections/azure/azcollection

# credential object dumped:
{'credentials': <msrestazure.azure_active_directory.MSIAuthentication object at 0x7f1f38d64c40>, 'subscription_id': 'XYZ-EDITED-XXYZ'}

[WARNING]:  * Failed to parse /work/env.azure_rm.yml with ansible_collections.azure.azcollection.plugins.inventory.azure_rm plugin: 'credential'
  File "/home/jenkins/.local/lib/python3.9/site-packages/ansible/inventory/manager.py", line 290, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/home/jenkins/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 219, in parse
    self._credential_setup()
  File "/home/jenkins/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 240, in _credential_setup
    self.azure_auth = AzureRMAuth(**auth_options)
  File "/home/jenkins/.ansible/collections/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1513, in __init__

# root cause of the issue 
    self.azure_credential_track2 = self.credentials['credential']
[WARNING]: Unable to parse /work/env.azure_rm.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
```

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME

azurerm inventory plugin

### CODE REVIEW

**Comment by Fred-sun** [comment]
@danielino Thank you for submitting this question, it is the same, it is assigned on 1619. The purpose was to separate SDK1 from SDK2 so that SDK1 could be deleted directly in the future. Thank you very much!

```e.g.
https://github.com/ansible-collections/azure/blob/103ab19e3bdd513f9635cdce2aee74d6667edbc2/plugins/module_utils/azure_rm_common.py#L1619

**Comment by Fred-sun** [comment]
@danielino Thank you for your contribution, your description is reasonable, I will promote the merger as soon as possible!

**Comment by Fred-sun** [comment]
@danielino You can also delete the following line from the PR because "credential" is not being referenced. Thank you very much!
https://github.com/ansible-collections/azure/blob/103ab19e3bdd513f9635cdce2aee74d6667edbc2/plugins/module_utils/azure_rm_common.py#L1619

**Comment by danielino** [comment]
ok, i have removed the line 1619. thank you

**Review by djcldcvr — COMMENTED** [review]
Getting following error while running playbook with ansible version ansible "2.10.17", azure.azcollection "1.12.0" & community.general  "4.6.1" !!

TypeError: __init__() got an unexpected keyword argument 'credential'

**Comment by Fred-sun** [comment]
@djcldcvr Could you please help to provide detailed logs? We tested this rigorously when we upgraded the SDK. Is it possible that you have updated the azcollection version, but the dependency has not been updated. Thank you very much!

**Pull request merged**
