### PR TITLE
support python 3.8

### LINKED ISSUE #139: Collection fails with python 3.8
##### SUMMARY

On Python 3.8 (the default on Ubuntu 20.04) this collection fails because is transitively using deprecated python functions.

This was fixed 6 months ago in https://github.com/Azure/azure-cli/issues/11239 in `azure-cli-core = ">=2.0.77"` but this collection wants `azure-cli-core = "==2.0.35"`

Looking through the requirements.txt listed here, it looks like we're kinda far behind.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Any

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below
DEFAULT_LOAD_CALLBACK_PLUGINS(~/.ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(~/.ansible.cfg) = yaml
INTERPRETER_PYTHON(~/.ansible.cfg) = auto
```

##### OS / ENVIRONMENT
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

##### STEPS TO REPRODUCE

```sh
$ virtualenv -p /usr/bin/python3.8 /tmp/foobar
$ cd /tmp/foobar
$ . bin/activate
# this is the current head of the dev branch
$ pip install -r https://raw.githubusercontent.com/ansible-collections/azure/234d9fc70097eb4481fe98c05580c9850c431798/requirements-azure.txt
$ ansible-galaxy collection install azure.azcollection --force
Installing 'azure.azcollection:0.1.3'
$ ansible -vvv  \
  -c local -e ansible_python_interpreter=/tmp/foobar/bin/python3 \
  -i localhost, all \
  -m azure.azcollection.azure_rm_resourcegroup -a "name=foobar location=eastus2" 
$ ansible -c local -i localhost, all -m azure.azcollection.azure_rm_resourcegroup -a "name=foobar location=eastus2" -vvv

...

<localhost> EXEC /bin/sh -c '/tmp/foobar/bin/python3 /home/njbird/.ansible/tmp/ansible-tmp-1590766242.1559303-3640414-175026806580758/AnsiballZ_azure_rm_resourcegroup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/njbird/.ansible/tmp/ansible-tmp-1590766242.1559303-3640414-175026806580758/ > /dev/null 2>&1 && sleep 0'          
The full traceback is:                                                                                                                                                                 
Traceback (most recent call last):
  File "/home/njbird/.ansible/tmp/ansible-tmp-1590766242.1559303-3640414-175026806580758/AnsiballZ_azure_rm_resourcegroup.py", line 102, in <module>
    _ansiballz_main()
  File "/home/njbird/.ansible/tmp/ansible-tmp-1590766242.1559303-3640414-175026806580758/AnsiballZ_azure_rm_resourcegroup.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/njbird/.ansible/tmp/ansible-tmp-1590766242.1559303-3640414-175026806580758/AnsiballZ_azure_rm_resourcegroup.py", line 40, in invoke_module

...

  File "/tmp/ansible_azure.azcollection.azure_rm_resourcegroup_payload_wu2wgs7f/ansible_azure.azcollection.azure_rm_resourcegroup_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1359, in _get_azure_cli_credentials
  File "/tmp/foobar/lib/python3.8/site-packages/azure/common/credentials.py", line 46, in get_azure_cli_credentials
    profile = get_cli_profile()
  File "/tmp/foobar/lib/python3.8/site-packages/azure/common/credentials.py", line 29, in get_cli_profile
    return Profile(storage=ACCOUNT)
  File "/tmp/foobar/lib/python3.8/site-packages/azure/cli/core/_profile.py", line 125, in __init__
    self.cli_ctx = cli_ctx or get_default_cli()
  File "/tmp/foobar/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 485, in get_default_cli
    return AzCli(cli_name='az',
  File "/tmp/foobar/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 52, in __init__
    SESSION.load(os.path.join(azure_folder, 'az.sess'), max_age=3600)
  File "/tmp/foobar/lib/python3.8/site-packages/azure/cli/core/_session.py", line 37, in load
    if st.st_mtime + max_age < time.clock():
AttributeError: module 'time' has no attribute 'clock'

```

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Update requirement file. Try to fixes #139 
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

azure_rm_mariadbserver
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by UnwashedMeme** [comment]
`azure-cli-core==2.11.1` requires (amongst others) 

* `azure-mgmt-resource==10.2.0`
* `msrestazure>=0.6.3`

but the requirements-azure.txt after this change has

* `azure-mgmt-resource==2.1.0`
* `msrestazure==0.6.2`

Presumably those requirements were increased in the `azure-cli-core` for a reason, but even if not this causes problems for tools like `pipenv` or others that implement dependency resolvers.

**Comment by uda** [comment]
Hi, thanks, this allowed me to run the code under python 3.8.5, although there are some dependency incompatibilities:

```
ERROR: azure-cli-core 2.11.1 has requirement azure-mgmt-resource==10.2.0, but you'll have azure-mgmt-resource 2.1.0 which is incompatible.
ERROR: azure-cli-core 2.11.1 has requirement msrestazure>=0.6.3, but you'll have msrestazure 0.6.2 which is incompatible.
```

Both azure-cli-core requirements are overridden by direct requirements in `requirements-azure.txt`, I won't say they should be removed, since they are used in the code, but maybe don't use strict version requirement for them.

**Comment by uda** [comment]
This change helped me run it on python 3.8.5, but what @UnwashedMeme wrote...

I won't say to remove them from `requirements-azure.txt` since they are used directly in code, but perhaps use open or loose version specification.

**Comment by Fred-sun** [comment]
> `azure-cli-core==2.11.1` requires (amongst others)
> 
> * `azure-mgmt-resource==10.2.0`
> * `msrestazure>=0.6.3`
> 
> but the requirements-azure.txt after this change has
> 
> * `azure-mgmt-resource==2.1.0`
> * `msrestazure==0.6.2`
> 
> Presumably those requirements were increased in the `azure-cli-core` for a reason, but even if not this causes problems for tools like `pipenv` or others that implement dependency resolvers.

@UnwashedMeme Thanks for your feedback! I have update azure-mgmt-resource version!

**Comment by UnwashedMeme** [comment]
@Fred-sun please don't forget `msrestazure` needs updating as well.

Is there any work to upgrade all of the azure libraries to more recent/latest version? Do this more systematically?

**Comment by Fred-sun** [comment]
> @Fred-sun please don't forget `msrestazure` needs updating as well.
> 
> Is there any work to upgrade all of the azure libraries to more recent/latest version? Do this more systematically?

This cannot be done, because some package updates will cause the api return value to be different, which requires testing before updating. Thank you!

**Pull request merged**
