### PR TITLE
Add private_dns_zone_id for azure_rm_privateendpointdnszonegroup

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Add private_dns_zone_id for azure_rm_privateendpointdnszonegroup 

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

azure_rm_privateendpointdnszonegroup.py
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by adthorn — APPROVED** [review]
Looks like it would fix my problem! It complains about the zone not being located in that subscription and if I put the whole var in the it adds /subscription to the full length. This should resolve it

**Review by adthorn — APPROVED** [review]

**Review by adthorn — APPROVED** [review]

**Review by adthorn — DISMISSED** [review]
Looks like it would fix my problem! It complains about the zone not being located in that subscription and if I put the whole var in the it adds /subscription to the full length. This should resolve it

**Comment by adthorn** [comment]
Can anyone review this? I'd like to be able to try it out asap.

**Comment by xuzhang3** [comment]
LGTM

**Pull request merged**
