### PR TITLE
Add license type for RHEL/SLES Azure Hybrid Benefit

### LINKED ISSUE #411: RedHat Azure Hybrid Benefit
##### SUMMARY

Hi,

we're trying to enable this little check box here for RedHat Linux machines on Azure, which in the ARM template seems to be the `license_type` attribute.
For RedHat this seems to be `RHEL_BYOS`, [see FAQ](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/azure-hybrid-benefit-linux#frequently-asked-questions)

> 
> Q: Can I use Azure Hybrid Benefit on VMs deployed from Azure Marketplace RHEL and SLES SAP images?
> 
> A: Yes, you can. You can use the license type of `RHEL_BYOS` for RHEL VMs and `SLES_BYOS` for conversions of VMs deployed from Azure Marketplace RHEL and SLES SAP images.
> 

grafik

This attribute is also available in the `azure_rm_virtualmachine` module, but is limited to `Windows_Server` and `Windows_Client`.
https://github.com/ansible-collections/azure/blob/673407a4fde49c232bf282c47be2781ee37ed1dc/plugins/modules/azure_rm_virtualmachine.py#L835

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`azure_rm_virtualmachine`

##### ANSIBLE VERSION

```paste below
ansible 2.9.17
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/$USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
# roles_path = /etc/ansible/roles:${PWD}/private-roles/:${PWD}/../private-roles/
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = ['/etc/ansible/roles', '--%<--', '--%<--'] 
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT

RHEL 8, Azure.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

### PR DESCRIPTION
**Pull request by ciis0**
##### SUMMARY

Fixes #411

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/azure-hybrid-benefit-linux

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
@ciis0 Now the old SDK is still used, which does not support Rehal's license. Hold the Issue and PR for the time being. thank you

**Comment by gundalow** [comment]
> @ciis0 Now the old SDK is still used, which does not support Rehal's license. Hold the Issue and PR for the time being. thank you

@Fred-sun What do you think is the best way forward for this PR?

**Comment by Fred-sun** [comment]
> > @ciis0 Now the old SDK is still used, which does not support Rehal's license. Hold the Issue and PR for the time being. thank you
> 
> @Fred-sun What do you think is the best way forward for this PR?

@gundalow Merge this PR and notice it in the documentation to temporarily disable both options. Once supported, update the documentation to indicate support for both options! Thank you very much!

**Comment by Fred-sun** [comment]
This pull request will be updated to the dev branch after the #672 merge.

**Comment by Fred-sun** [comment]
@ciis0 Please add it to document synchronously. Thank you very much!
```e.g.
        choices:
            - Windows_Server
            - Windows_Client
            - RHEL_BYOS
            - SLES_BYOS

**Comment by ciis0** [comment]
oops, seems I deleted my fork. I'll try to recreate it or create a new PR.

**Comment by Fred-sun** [comment]
> oops, seems I deleted my fork. I'll try to recreate it or create a new PR.

@ciis0 What's the action?

**Comment by ciis0** [comment]
Recreated as #804

**Pull request closed without merging**
