### PR TITLE
Bump version to v1.13.0

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Bump version to v1.13.0

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Fred-sun** [comment]
ready_for_review

**Comment by Xiuxi-Sun** [comment]
ping @Fred-sun

**Comment by Xiuxi-Sun** [comment]
@Fred-sun

**Comment by Xiuxi-Sun** [comment]
@Fred-sun

**Comment by Fred-sun** [comment]
@Xiuxi-Sun

**Comment by Xiuxi-Sun** [comment]
@Fred-sun

**Comment by Xiuxi-Sun** [comment]
@Fred-sun

**Comment by xuzhang3** [comment]
LGTM

**Pull request merged**
