### PR TITLE
Support managed flexible server

### PR DESCRIPTION
**Pull request by Fred-sun**
##### SUMMARY

Support managed flexible server

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

azure_rm_mysqlflexibleserver.py
azure_rm_mysqlflexibleserver_info.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by p3ck** [comment]
Is there a reason this is on Hold? 

Thanks

**Comment by Fred-sun** [comment]
@p3ck Still under development, will be completed soon! Thank you!

**Comment by Fred-sun** [comment]
ready_for_review!

**Comment by xtonousou** [comment]
Any updates?

**Comment by Fred-sun** [comment]
@xtonousou Due to regional quota restrictions, this resource cannot be tested for the time being and is currently being processed once it is completed. Merger will proceed as soon as possible! Thank you!

**Review by xuzhang3 — APPROVED** [review]

**Pull request merged**
