### PR TITLE
updated code to fetch availability zone info into hostvars

### PR DESCRIPTION
**Pull request by ShwetaliBerad**
##### SUMMARY
updated code to fetch availability zone info into hostvars via Azure Inventory Script
#161 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
Dynamic Inventory Script

### CODE REVIEW

**Comment by ShwetaliBerad** [comment]
@Fred-sun could you please assign reviewer for this PR ?

**Comment by ShwetaliBerad** [comment]
@Fred-sun Could you please look into this PR ?

**Comment by Fred-sun** [comment]
Yes, the review of this PR was delayed due to other issues recently, and I will focus on review tomorrow. Thank you!

**Comment by Fred-sun** [comment]
@ShwetaliBerad Thank you for your contribution. What is the purpose of this parameter? Can you give us a sample for this parameter?

**Comment by ShwetaliBerad** [comment]
> @ShwetaliBerad Thank you for your contribution. What is the purpose of this parameter? Can you give us a sample for this parameter?
Screenshot from 2020-09-11 13-58-02

@Fred-sun 
This parameter will give the availability zone value in which the particular VM resides. On Azure, while creating VM , we can set Availability option as availability zone, and we can select availability zone value as 1 or 2 or 3. An availability zone is a physically separate zone in an Azure region. It is a high-availability offering that protects your applications and data from datacenter failures. If we choose availability zone for particular VM, then managed disk and public IP (if you have one) will be created in the same availability zone as your virtual machine.
API Response for VM in availability zone '1' is as follows : 
{
  "name": "test",
  "id": "<vm_id>",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "southeastasia",
   .......<other properties>.....
   "zones": [
    "1"
  ]
}

**Comment by Fred-sun** [comment]
@ShwetaliBerad I will review it again. Thank you very much!

**Comment by Fred-sun** [comment]
Hi @ShwetaliBerad No problem, but it only supports the ansible version after 2.10. Ansible/plugin/inventory/azure_rm.py will be used before 2.10, thanks!

If you want ansible 2.9 to also support it, you need to add patch to 2.9 and modify ansible/plugin/inventory/azure_rm.py.

**Comment by Fred-sun** [comment]
I will advance the merger. Thank you!

**Comment by haiyuazhang** [comment]
@ShwetaliBerad  thanks for contributing to the azure collection! According to @Fred-sun 's testing result, this PR will only enable this feature in ansible 2.10+. If your target ansible version is 2.9, then the same change need to be made in ansible 2.9, what you need to do is submit a similar PR targeting ansible2.9-stable. I'll close and merge this one anyway.

**Pull request merged**
