### PR TITLE
add public_ip_per_vm parameter for azure_rm_virtualmachinescaleset

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
##### SUMMARY
* add `public_ip_per_vm` parameter for azure_rm_virtualmachinescaleset module, to match Azure CLI `az vmss create --public-ip-per-vm` parameter

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
azure_rm_virtualmachinescaleset

### CODE REVIEW

**Comment by andreasgerstmayr** [comment]
Moved from https://github.com/ansible/ansible/pull/64798.
Unfortunately I couldn't test it, because I'm getting the following error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine ansiblevmss - Azure Error: InvalidParameter\nMessage: Required parameter 'osProfile' is missing (null).\nTarget: osProfile"}
```
also without applying this PR.

```
  tasks:
    - azure_rm_virtualmachinescaleset:
        resource_group: Builds
        name: ansiblevmss
        vm_size: Standard_DS1_v2
        capacity: 1
        upgrade_policy: Manual
        image:
          name: image-fedora31
          resource_group: Builds
        virtual_network_name: az-network
        subnet_name: az-subnet
```

**Comment by Fred-sun** [comment]
@andreasgerstmayr Thank you for taking the time to report this problem. Could you please help explain the function of adding this parameter? What do you want to do with this parameter? Thank you very much!

**Comment by andreasgerstmayr** [comment]
hi @Fred-sun, usually all machines of the virtual machine scale set get internal IPs assigned. With this option, each machine gets a public IP address assigned. It behaves in the same way as `az vmss create --public-ip-per-vm` (see https://docs.microsoft.com/en-us/cli/azure/vmss?view=azure-cli-latest#az-vmss-create)

**Comment by Fred-sun** [comment]
@andreasgerstmayr Thank you for your information. I will test as soon as possible. Once passed, I will push forward the review and merge.

**Comment by Fred-sun** [comment]
@andreasgerstmayr The test passed, I will push forward the review and merger as soon as possible. Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Please help review and push for the PR merge when you're free! Thank you very much!
My PlayBook as follow:
```e.g.
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: testVnet0003
        address_prefixes: "10.0.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: testSubnet003
        address_prefix: "10.0.1.0/24"
        virtual_network: testVnet0003
    - name: Create VMSS
      azure_rm_virtualmachinescaleset:
        resource_group: "{{ resource_group }}"
        name: testVMSS003
        vm_size: Standard_B1s
        admin_username: testuser
        admin_password: "Password1234!"
        capacity: 1
        virtual_network_name: testVnet0003
        subnet_name: testSubnet003
        upgrade_policy: Manual
        public_ip_per_vm: True
        image:
          offer: CoreOS
          publisher: CoreOS
          sku: Stable
          version: latest

**Pull request merged**
