### PR TITLE
Add rewrite rule capability to appgateway module

### PR DESCRIPTION
**Pull request by l3ender**
##### SUMMARY
This PR adds the ability to configure rewrite rules on a v2 application gateway.

The PR also clarifies other parameter usage for the module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
azure_rm_appgateway

##### ADDITIONAL INFORMATION
Rewrite rules are only allowed on v2 application gateways.

Example snippet of usage:
```yaml
- name: Try to create v2 instance of Application Gateway with rewrite rules - update rewrite rule
  azure_rm_appgateway:
    resource_group: my-rg
    name: my-v2-appgateway
    rewrite_rule_sets:
      - name: "configure-headers"
        rewrite_rules:
          - name: "add-security-response-header"
            rule_sequence: 1
            action_set:
              response_header_configurations:
                - header_name: "Strict-Transport-Security"
                  header_value: "max-age=31536000"
          - name: "remove-backend-response-headers"
            rule_sequence: 2
            action_set:
              response_header_configurations:
                - header_name: "Server"
                - header_name: "X-Powered-By"
          - name: "set-custom-header-condition"
            rule_sequence: 3
            conditions:
              - variable: "var_client_ip"
                pattern: "1.1.1.1"
              - variable: "http_req_Authorization"
                pattern: "12345"
                ignore_case: false
            action_set:
              request_header_configurations:
                - header_name: "Foo"
                  header_value: "BarUpdated"
              response_header_configurations:
                - header_name: "FooResponse"
                  header_value: "BarResponse"
```

### CODE REVIEW

**Comment by l3ender** [comment]
Hello @Fred-sun, please take a look at this PR. Thank you!

**Comment by Fred-sun** [comment]
@l3ender Please! similar chage for 2.10.txt, 2.12.txt, 2.13.txt and 2.9.txt
```e.g.
ERROR: plugins/modules/azure_rm_appgateway.py:0:0: import-error: Exception attempting to import module for argument_spec introspection, 'cannot import name 'is_valid_resource_id' from 'ansible_collections.azure.azcollection.plugins.module_utils.azure_rm_common' (/home/vsts/.ansible/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py)'
ERROR: tests/sanity/ignore-2.12.txt:11:1: A100: Ignoring 'doc-choices-do-not-match-spec' on 'plugins/modules/azure_rm_appgateway.py' is unnecessary
ERROR: tests/sanity/ignore-2.12.txt:12:1: A100: Ignoring 'parameter-type-not-in-doc' on 'plugins/modules/azure_rm_appgateway.py' is unnecessary
ERROR: tests/sanity/ignore-2.12.txt:13:1: A100: Ignoring 'parameter-list-no-elements' on 'plugins/modules/azure_rm_appgateway.py' is unnecessary
ERROR: tests/sanity/ignore-2.12.txt:14:1: A100: Ignoring 'doc-elements-mismatch' on 'plugins/modules/azure_rm_appgateway.py' is unnecessary

**Comment by l3ender** [comment]
@Fred-sun It is updated, thank you! My apologies for missing the sanity errors.

**Comment by l3ender** [comment]
Hi @Fred-sun, any update on this PR?

**Comment by xuzhang3** [comment]
@l3ender  Can you help resolve the conflict?

**Comment by l3ender** [comment]
@xuzhang3 Conflict is resolved, thank you!

**Comment by xuzhang3** [comment]
LGTM

**Comment by xuzhang3** [comment]
@l3ender  Another conflict after other PR merged,  please help resolve this conflict thanks.

**Comment by l3ender** [comment]
@xuzhang3 It's resolved--thank you!

**Comment by xuzhang3** [comment]
LGTM, shipping it

**Pull request merged**
